#!/bin/bash

TAB='\t';
NULO='\\N';
LIDOS='lidos/';
SQLCOPY='sqlCopy/';


FILE=$1;
echo "COPY financeiro.*************(***********) FROM stdin WITH NULL AS '${NULO}';" >> ${FILE}.sql;

#file_length=`wc -l '${FILE}' | cut -c1-5`;


cat ${FILE} | grep ^[^SC*] | while read LINHA;
do 

    ITCOUSUARIO=${CONSTANTE:0:11};
    
    ITCOTERMINALUSUARIO=${LINHA:11:8};

    ITDATRANSACAO=${LINHA:19:8};

    ITHOTRANSACAO=${LINHA:27:4};

    ITCOUGOPERADOR=${LINHA:31:6};

    ITINOPERACAO=${LINHA:37:1};

    GRUGGESTAOANNUMEROLF=${LINHA:38:23};

    ITINSITUACAOLISTA=${LINHA:61:1};

    ITVAAUX=${LINHA:62:17};

    ITNUISNDOCHABIL=${LINHA:79:8};

    ITCORECOLHEDOR=${LINHA:87:980};

    ITVABASECALCULO=${LINHA:1067:1190};

    ITVARECOLHIDO=${LINHA:2257:1190};

    ITVAJUROS=${LINHA:3447:1190};

    ITVAMULTA=${LINHA:4637:1190};

    ITNUDARF=${LINHA:5827:840};

    ITPERECEITA=${LINHA:6667:5};

    GRUGGESTAOLISTAORIGEM=${LINHA:6672:23};

    GRUGGESTAOLISTADESTINO=${LINHA:6695:23};

    ITCOUSUARIOTRAN=${LINHA:6718:11};

    ITCOUGOPERADORTRAN=${LINHA:6729:6};

    GRUGGESTAOTRANSFERENCIA=${LINHA:6735:11};

    ITNULISTATRANSFERENCIA=${LINHA:6746:6};

    ITNUDARFCANCELADO=${LINHA:6752:840};

    FILLER=${LINHA:7592:108};


    echo -e $ITCOUSUARIO${TAB}$ITCOTERMINALUSUARIO${TAB}$ITDATRANSACAO${TAB}$ITHOTRANSACAO${TAB}$ITCOUGOPERADOR${TAB}$ITINOPERACAO${TAB}$GRUGGESTAOANNUMEROLF${TAB}$ITINSITUACAOLISTA${TAB}$ITVAAUX${TAB}$ITNUISNDOCHABIL${TAB}$ITCORECOLHEDOR${TAB}$ITVABASECALCULO${TAB}$ITVARECOLHIDO${TAB}$ITVAJUROS${TAB}$ITVAMULTA${TAB}$ITNUDARF${TAB}$ITPERECEITA${TAB}$GRUGGESTAOLISTAORIGEM${TAB}$GRUGGESTAOLISTADESTINO${TAB}$ITCOUSUARIOTRAN${TAB}$ITCOUGOPERADORTRAN${TAB}$GRUGGESTAOTRANSFERENCIA${TAB}$ITNULISTATRANSFERENCIA${TAB}$ITNUDARFCANCELADO${TAB}$FILLER >> ${FILE}.sql;

done
mv ${FILE} ${LIDOS};
tar -cf ${LIDOS}${FILE}".tar.gz" ${LIDOS}${FILE}
rm ${LIDOS}${FILE}
mv ${FILE}.sql ${SQLCOPY}/${FILE}.sql;

