#!/bin/bash

TAB='\t';
NULO='\\N';
LIDOS='lidos/';
SQLCOPY='sqlCopy/';


FILE=$1;
echo "COPY financeiro.*************(***********) FROM stdin WITH NULL AS '${NULO}';" >> ${FILE}.sql;

#file_length=`wc -l '${FILE}' | cut -c1-5`;


cat ${FILE} | grep ^[^SC*] | while read LINHA;
do 

    ITCOUSUARIO=${CONSTANTE:0:11};
    
    ITDATRANSACAO=${LINHA:11:8};

    ITHOTRANSACAO=${LINHA:19:4};

    ITCOUGOPERADOR=${LINHA:23:6};

    ITINOPERACAO=${LINHA:29:1};

    ITCOUNIDADEGESTORA=${LINHA:30:6};

    ITCOGESTAO=${LINHA:36:5};

    ITNUPRECATORIO=${LINHA:41:30};

    ITCOBENEFICIARIO=${LINHA:71:14};

    ITNOBENEFICIARIO=${LINHA:85:60};

    ITANPROPOSTAORCAMENTARIA=${LINHA:145:4};

    ITCOORGAOREU=${LINHA:149:5};

    ITCOBANCO=${LINHA:154:3};

    ITCOAGENCIA=${LINHA:157:4};

    ITNUCONTA=${LINHA:161:13};

    ITVAPARCELAORIGINAL=${LINHA:174:170};

    ITVAPARCELAATUAL=${LINHA:344:170};

    ITDAPREVISAOVENCIMENTO=${LINHA:514:80};

    ITNULISTABENEFICIARIO=${LINHA:594:230};

    ITNUOBPAGAMENTO=${LINHA:824:230};

    ITDAOBPAGAMENTO=${LINHA:1133:2300};

    ITNULISTACANCELADA=${LINHA:3434:2300};

    ITNUOBCANCELADA=${LINHA:5734:800};

    ITNUPARCELACOMPLEMENTO=${LINHA:6534:20};

    ITSQCOMPLEMENTO=${LINHA:6554:20};

    ITVACOMPLEMENTO=${LINHA:6574:170};

    ITVACOMPLEMENTORETENCAO=${LINHA:6744:170};

    ITDACOMPLEMENTOVENCIMENTO=${LINHA:6914:80};

    ITNULISTABENEFICIARIOCOMPLEMEN=${LINHA:6994:230};

    ITNUOBPAGAMENTOCOMPLEM=${LINHA:7224:230};

    ITDAOBPAGAMENTOCOMPLEM=${LINHA:7454:80};

    ITNULISTACANCELADACOMPLEM=${LINHA:7534:2300};

    ITNUOBCANCELADACOMPLEM=${LINHA:9834:2300};

    ITDAOBCANCELADACOMPLEM=${LINHA:12134:800};

    ITNUPARCELADEVOLUCAO=${LINHA:12934:20};

    ITSQDEVOLUCAO=${LINHA:12954:20};

    ITVADEVOLUCAO=${LINHA:12974:170};

    ITNUDOCUMENTODEVOLUCAO=${LINHA:13144:230};

    ITINOPERACAODEVOLUCAO=${LINHA:13374:10};

    FILLER=${LINHA:13384:616};


    echo -e $ITCOUSUARIO${TAB}$ITDATRANSACAO${TAB}$ITHOTRANSACAO${TAB}$ITCOUGOPERADOR${TAB}$ITINOPERACAO${TAB}$ITCOUNIDADEGESTORA${TAB}$ITCOGESTAO${TAB}$ITNUPRECATORIO${TAB}$ITCOBENEFICIARIO${TAB}$ITNOBENEFICIARIO${TAB}$ITANPROPOSTAORCAMENTARIA${TAB}$ITCOORGAOREU${TAB}$ITCOBANCO${TAB}$ITCOAGENCIA${TAB}$ITNUCONTA${TAB}$ITVAPARCELAORIGINAL${TAB}$ITVAPARCELAATUAL${TAB}$ITDAPREVISAOVENCIMENTO${TAB}$ITNULISTABENEFICIARIO${TAB}$ITNUOBPAGAMENTO${TAB}$ITDAOBPAGAMENTO${TAB}$ITNULISTACANCELADA${TAB}$ITNUOBCANCELADA${TAB}$ITDAOBCANCELADA${TAB}$ITNUPARCELACOMPLEMENTO${TAB}$ITSQCOMPLEMENTO${TAB}$ITVACOMPLEMENTO${TAB}$ITVACOMPLEMENTORETENCAO${TAB}$ITDACOMPLEMENTOVENCIMENTO${TAB}$ITNULISTABENEFICIARIOCOMPLEMEN${TAB}$ITNUOBPAGAMENTOCOMPLEM${TAB}$ITDAOBPAGAMENTOCOMPLEM${TAB}$ITNULISTACANCELADACOMPLEM${TAB}$ITDAOBCANCELADACOMPLEM${TAB}$ITNUPARCELADEVOLUCAO${TAB}$ITSQDEVOLUCAO${TAB}$ITVADEVOLUCAO${TAB}$ITNUDOCUMENTODEVOLUCAO${TAB}$ITINOPERACAODEVOLUCAO${TAB}$FILLER >> ${FILE}.sql;

done
mv ${FILE} ${LIDOS};
tar -cf ${LIDOS}${FILE}".tar.gz" ${LIDOS}${FILE}
rm ${LIDOS}${FILE}
mv ${FILE}.sql ${SQLCOPY}/${FILE}.sql;

