#!/bin/bash

TAB='\t';
NULO='\\N';
LIDOS='lidos/';
SQLCOPY='sqlCopy/';

FILE=$1;
echo "COPY financeiro.*************(***********) FROM stdin WITH NULL AS '${NULO}';" >> ${FILE}.sql;

#file_length=`wc -l '${FILE}' | cut -c1-5`;


cat ${FILE} | grep ^[^SC*] | while read LINHA;
do 

    COUSUARIO=${CONSTANTE:0:11};
    
    COTERMINALUSUARIO=${LINHA:11:8}

    DTTRANSACAO=${LINHA:19:8}

    NOTRANSACAO=${LINHA:27:4}

    COUGOPERADOR=${LINHA:31:6}

    UGGESTAONUMERONEUQ=${LINHA:37:23}

    DTEMISSAO=${LINHA:60:8}

    INFAVORECIDO=${LINHA:68:1}

    COFAVORECIDO=${LINHA:69:14}

    TXOBSERVACAO=${LINHA:83:234}

    GREVENTO=${LINHA:317:6}

    INESFERAORACAMENTARIA=${LINHA:323:1}

    COPROGRAMATRABALHORESUMIDO=${LINHA:324:6}

    FONTERECURSO=${LINHA:330:10}

    NATUREZADESPESA=${LINHA:340:6}

    COUGRESPONSAVEL=${LINHA:346:6}

    COPLANOINTERNO=${LINHA:352:11}

    VATRANSACAO=${LINHA:363:17}

    INMODALIDADELICITACAO=${LINHA:380:2}

    INEMPENHO=${LINHA:382:1}

    TXREFERENCIADISPENSA=${LINHA:383:20}

    INORIGEMMATERIAL=${LINHA:403:1}

    NUPROCESSO=${LINHA:404:20}

    COUFBENEFICIADA=${LINHA:424:2}

    COMUNICIPIOBENEFICIADA=${LINHA:426:4}

    COINCISO=${LINHA:430:2}

    TXAMPAROLEGAL=${LINHA:432:8}

    NUDOCUMENTOREFERENCIA=${LINHA:440:12}

    INEMISSAO=${LINHA:452:1}

    MELANCAMENTO=${LINHA:453:2}

    VACRONOGRAMA=${LINHA:453:204}

    COUGDOCREFERENCIA=${LINHA:659:6}

    COGESTAODICREFERENCIA=${LINHA:665:5}

    INCONTRAENTREGANE=${LINHA:670:1}

    INSITUACAOCREDORSICAF=${LINHA:671:2}

    DATAVENCIMENTO=${LINHA:673:96}

    DATAPAGAMENTO=${LINHA:769:96}

    VACRONOGRAMADO=${LINHA:865:204}

    COMSGDOCUMENTO=${LINHA:1069:3}

    INPAGAMENTOPRECATORIO=${LINHA:1072:1}

    NUPRECATORIO=${LINHA:1073:20}

    NUORIGINAL=${LINHA:1093:20}

    DATAATUALIZACAO=${LINHA:1113:8}

    INATUALIZACAO=${LINHA:1121:1}

    NULISTA=${LINHA:1122:120}

    INLIQUIDACAO=${LINHA:1242:1}

    COSISTEMAORIGEM=${LINHA:1243:10}

    DICRONOGRAMA=${LINHA:1253:24}

    QTLANCAMENTO=${LINHA:1277:3}

    FILLER=${LINHA:1280:20}


    echo -e $COUSUARIO${TAB}$COTERMINALUSUARIO${TAB}$DTTRANSACAO${TAB}$NOTRANSACAO${TAB}$COUGOPERADOR${TAB}$UGGESTAONUMERONEUQ${TAB}$DTEMISSAO${TAB}$INFAVORECIDO${TAB}$COFAVORECIDO${TAB}$TXOBSERVACAO${TAB}$GREVENTO${TAB}$INESFERAORACAMENTARIA${TAB}$COPROGRAMATRABALHORESUMIDO${TAB}$FONTERECURSO${TAB}$NATUREZADESPESA${TAB}$COUGRESPONSAVEL${TAB}$COPLANOINTERNO${TAB}$VATRANSACAO${TAB}$INMODALIDADELICITACAO${TAB}$INEMPENHO${TAB}$TXREFERENCIADISPENSA${TAB}$INORIGEMMATERIAL${TAB}$NUPROCESSO${TAB}$COUFBENEFICIADA${TAB}$COMUNICIPIOBENEFICIADA${TAB}$COINCISO${TAB}$TXAMPAROLEGAL${TAB}$NUDOCUMENTOREFERENCIA${TAB}$INEMISSAO${TAB}$MELANCAMENTO${TAB}$VACRONOGRAMA${TAB}$COUGDOCREFERENCIA${TAB}$COGESTAODICREFERENCIA${TAB}$INCONTRAENTREGANE${TAB}$INSITUACAOCREDORSICAF${TAB}$DATAVENCIMENTO${TAB}$DATAPAGAMENTO${TAB}$VACRONOGRAMADO${TAB}$COMSGDOCUMENTO${TAB}$INPAGAMENTOPRECATORIO${TAB}$NUPRECATORIO${TAB}$NUORIGINAL${TAB}$DATAATUALIZACAO${TAB}$INATUALIZACAO${TAB}$NULISTA${TAB}$INLIQUIDACAO${TAB}$COSISTEMAORIGEM${TAB}$DICRONOGRAMA${TAB}$QTLANCAMENTO${TAB}$FILLER >> ${FILE}.sql;

done
mv ${FILE} ${LIDOS};
tar -cf ${LIDOS}${FILE}".tar.gz" ${LIDOS}${FILE}
rm ${LIDOS}${FILE}
mv ${FILE}.sql ${SQLCOPY}/${FILE}.sql;

