#!/bin/bash

TAB='\t';
NULO='\\N';
LIDOS='lidos/';
SQLCOPY='sqlCopy/';


FILE=$1;
echo "COPY financeiro.*************(***********) FROM stdin WITH NULL AS '${NULO}';" >> ${FILE}.sql;

#file_length=`wc -l '${FILE}' | cut -c1-5`;


cat ${FILE} | grep ^[^SC*] | while read LINHA;
do 

    ITCOUSUARIO=${CONSTANTE:0:11};
    
    ITCOTERMINALUSUARIO=${LINHA:11:8};

    ITDATRANSACAO=${LINHA:19:8};

    ITHOTRANSACAO=${LINHA:27:4};

    ITCOUGOPERADOR=${LINHA:31:6};

    ITCOBANCO=${LINHA:37:3};

    ITCOAGENCIA=${LINHA:40:3};

    ITNUCONTACORRENTE=${LINHA:43:10};

    GRUGGESTAOANNUMEROLP=${LINHA:54:23};

    ITNUSEQUENCIAL=${LINHA:77:6};

    ITVAPRECATORIO=${LINHA:83:17};

    ITNUPRECATORIO=${LINHA:100:30};

    ITINSITUACAOPRECATORIO=${LINHA:130:1};

    GRANNUOBCANCELAMENTOLP=${LINHA:131:12};

    GRANNUOBRESTABELECIMENTOLP=${LINHA:143:12};

    GRUGGESTAOCANCELAMENTOLP=${LINHA:156:11};

    ITINENVIOMENSAGEMSPB=${LINHA:166:1};

    ITVACANCELAMENTO=${LINHA:167:17};

    ITNUCONTROLESTRSPB=${LINHA:184:20};

    ITNUPARCELA=${LINHA:204:2};

    ITDASAQUEBACEN=${LINHA:206:8};

    ITNUOPERACAOSPB=${LINHA:214:23};

    ITSQITEMSPB=${LINHA:237:3};

    ITINRETORNOSPB=${LINHA:240:1};

    FILLER=${LINHA:241:59};


    echo -e $ITCOUSUARIO${TAB}$ITCOTERMINALUSUARIO${TAB}$ITDATRANSACAO${TAB}$ITHOTRANSACAO${TAB}$ITCOUGOPERADOR${TAB}$ITCOBANCO${TAB}$ITCOAGENCIA${TAB}$ITNUCONTACORRENTE${TAB}$GRUGGESTAOANNUMEROLP${TAB}$ITNUSEQUENCIAL${TAB}$ITVAPRECATORIO${TAB}$ITNUPRECATORIO${TAB}$ITINSITUACAOPRECATORIO${TAB}$GRANNUOBCANCELAMENTOLP${TAB}$GRANNUOBRESTABELECIMENTOLP${TAB}$GRUGGESTAOCANCELAMENTOLP${TAB}$ITINENVIOMENSAGEMSPB${TAB}$ITVACANCELAMENTO${TAB}$ITNUCONTROLESTRSPB${TAB}$ITNUPARCELA${TAB}$ITDASAQUEBACEN${TAB}$ITNUOPERACAOSPB${TAB}$ITSQITEMSPB${TAB}$ITINRETORNOSPB${TAB}$FILLER >> ${FILE}.sql;

done
mv ${FILE} ${LIDOS};
tar -cf ${LIDOS}${FILE}".tar.gz" ${LIDOS}${FILE}
rm ${LIDOS}${FILE}
mv ${FILE}.sql ${SQLCOPY}/${FILE}.sql;

