#!/bin/bash

TAB='\t';
NULO='\\N';
LIDOS='lidos/';
LENDO='Lendo/';
SQLCOPY='sqlCopy/';


FILE=$1;

cp ${FILE} ${LENDO}/${FILE};

cd ${LENDO}
echo -e "SET client_encoding TO 'LATIN5'; \n"  >> ../${FILE}.sql;
echo "COPY financeiro.notaempenho(ungcod, ptrcod, gstcod, ndpid, gstcodfavorecido, frccod, evecod, esfcod, ungcodresponsavel, ungcodfavorecido, ungcoddocreferencia, gstcoddocumentoreferencia, noeano, noenum, noedatavencimento, noedataemissao, noedatapagamento, noedataatualizacao, noedatatransacao, noetransacaovlr, noeobs, noeprocessonum, noeamparolegalnum, noeincisonum, noeprecatorionum, noepagprecatoriosit, noeoriginalnum, noelistanum, noedocreferenciaano, noedocreferencia, noeliquidacaosit, noecronogramavlr) FROM stdin WITH NULL AS '${NULO}';" >> ../${FILE}.sql;

#file_length=`wc -l '${FILE}' | cut -c1-5`;


cat ${FILE} | grep ^[^NE*]  | while read LINHA;
do 
    #echo $LINHA;
    CPFDOUSUARIO=${LINHA:0:11};
    CPFDOUSUARIO=`echo "$CPFDOUSUARIO" | sed "s/ //g"`;
	test -z $CPFDOUSUARIO;
	if [ $? == 0 ]; then
	CPFDOUSUARIO=${NULO};
	fi

    TERMINALDOUSUARIO=${LINHA:11:8};
    TERMINALDOUSUARIO=`echo "$TERMINALDOUSUARIO" | sed "s/ //g"`;
	test -z $TERMINALDOUSUARIO;
	if [ $? == 0 ]; then
	TERMINALDOUSUARIO=${NULO};
	fi

    DATADETRANSACAO=${LINHA:23:4}${LINHA:21:2}${LINHA:19:2};
    DATADETRANSACAO=`echo "$DATADETRANSACAO" | sed "s/ //g"`;
	test -z $DATADETRANSACAO;
	if [ $? == 0 ]; then
	DATADETRANSACAO=${NULO};
	fi

    HORATRANSACAO=${LINHA:27:4};
    HORATRANSACAO=`echo "$HORATRANSACAO" | sed "s/ //g"`;
	test -z $HORATRANSACAO;
	if [ $? == 0 ]; then
	HORATRANSACAO=${NULO};
	fi

    CODIGODAUGDOOPERADOR=${LINHA:31:6};
    CODIGODAUGDOOPERADOR=`echo "$CODIGODAUGDOOPERADOR" | sed "s/ //g"`;
	test -z $CODIGODAUGDOOPERADOR;
	if [ $? == 0 ]; then
	CODIGODAUGDOOPERADOR=${NULO};
	fi

    NUMERODANE=${LINHA:37:23};
    NUMERODANE=`echo "$NUMERODANE" | sed "s/ //g"`;
	test -z $NUMERODANE;
	if [ $? == 0 ]; then
	NUMERODANE=${NULO};
	fi

    NUMERODODOCREFERENCIA=${LINHA:60:12};
    NUMERODODOCREFERENCIA=`echo "$NUMERODODOCREFERENCIA" | sed "s/ //g"`;
	test -z $NUMERODODOCREFERENCIA;
	if [ $? == 0 ]; then
	NUMERODODOCREFERENCIA=${NULO};
	fi

    DATADEEMISSAO=${LINHA:76:4}${LINHA:74:2}${LINHA:72:2};
    DATADEEMISSAO=`echo "$DATADEEMISSAO" | sed "s/ //g"`;
	test -z $DATADEEMISSAO;
	if [ $? == 0 ]; then
	DATADEEMISSAO=${NULO};
	fi

    TIPODOFAVORECIDO=${LINHA:80:1};
    TIPODOFAVORECIDO=`echo "$TIPODOFAVORECIDO" | sed "s/ //g"`;
	test -z $TIPODOFAVORECIDO;
	if [ $? == 0 ]; then
	TIPODOFAVORECIDO=${NULO};
	fi

    CODIGODOFAVORECIDO=${LINHA:81:14};
    CODIGODOFAVORECIDO=`echo "$CODIGODOFAVORECIDO" | sed "s/ //g"`;
	test -z $CODIGODOFAVORECIDO;
	if [ $? == 0 ]; then
	CODIGODOFAVORECIDO=${NULO};
	fi

    OBSERVACAO=${LINHA:95:234};
    OBSERVACAO=`echo "$OBSERVACAO" | sed "s/ //g"`;
	test -z $OBSERVACAO;
	if [ $? == 0 ]; then
	OBSERVACAO=${NULO};
	fi

    CODIGODOEVENTO=${LINHA:329:6};
    CODIGODOEVENTO=`echo "$CODIGODOEVENTO" | sed "s/ //g"`;
	test -z $CODIGODOEVENTO;
	if [ $? == 0 ]; then
	CODIGODOEVENTO=${NULO};
	fi

    ESFERAORCAMENTARIA=${LINHA:335:1};
    ESFERAORCAMENTARIA=`echo "$ESFERAORCAMENTARIA" | sed "s/ //g"`;
	test -z $ESFERAORCAMENTARIA;
	if [ $? == 0 ]; then
	ESFERAORCAMENTARIA=${NULO};
	fi

    PROGRAMADETRABALHORESUMIDOPTRES=${LINHA:336:6};
    PROGRAMADETRABALHORESUMIDOPTRES=`echo "$PROGRAMADETRABALHORESUMIDOPTRES" | sed "s/ //g"`;
	test -z $PROGRAMADETRABALHORESUMIDOPTRES;
	if [ $? == 0 ]; then
	PROGRAMADETRABALHORESUMIDOPTRES=${NULO};
	fi

    FONTEDERECURSO=${LINHA:342:10};
    FONTEDERECURSO=`echo "$FONTEDERECURSO" | sed "s/ //g"`;
	test -z $CPFDOUSUARIO;
	if [ $? == 0 ]; then
	FONTEDERECURSO=${NULO};
	fi

    NATUREZADEDESPESA=${LINHA:352:6};
    NATUREZADEDESPESA=`echo "$NATUREZADEDESPESA" | sed "s/ //g"`;
	test -z $NATUREZADEDESPESA;
	if [ $? == 0 ]; then
	NATUREZADEDESPESA=${NULO};
	fi

    CODIGODAUGRESPONSAVEL=${LINHA:358:6};
    CODIGODAUGRESPONSAVEL=`echo "$CODIGODAUGRESPONSAVEL" | sed "s/ //g"`;
	test -z $CODIGODAUGRESPONSAVEL;
	if [ $? == 0 ]; then
	CODIGODAUGRESPONSAVEL=${NULO};
	fi

    PLANOINTERNO=${LINHA:364:11};
    PLANOINTERNO=`echo "$PLANOINTERNO" | sed "s/ //g"`;
	test -z $PLANOINTERNO;
	if [ $? == 0 ]; then
	PLANOINTERNO=${NULO};
	fi

    VALORDATRANSACAO=${LINHA:375:17};
    VALORDATRANSACAO=`echo "$VALORDATRANSACAO" | sed "s/ //g"`;
	test -z $VALORDATRANSACAO;
	if [ $? == 0 ]; then
	VALORDATRANSACAO=${NULO};
	fi

    MODALIDADEDELICITACAO=${LINHA:392:2};
    MODALIDADEDELICITACAO=`echo "$MODALIDADEDELICITACAO" | sed "s/ //g"`;
	test -z $MODALIDADEDELICITACAO;
	if [ $? == 0 ]; then
	MODALIDADEDELICITACAO=${NULO};
	fi

    TIPODENE=${LINHA:394:1};
    TIPODENE=`echo "$TIPODENE" | sed "s/ //g"`;
	test -z $TIPODENE;
	if [ $? == 0 ]; then
	TIPODENE=${NULO};
	fi

    REFERENCIADADISPENSA=${LINHA:395:19};
    REFERENCIADADISPENSA=`echo "$REFERENCIADADISPENSA" | sed "s/ //g"`;
	test -z $REFERENCIADADISPENSA;
	if [ $? == 0 ]; then
	REFERENCIADADISPENSA=${NULO};
	fi

    ORIGEMMATERIAL=${LINHA:415:1};
    ORIGEMMATERIAL=`echo "$ORIGEMMATERIAL" | sed "s/ //g"`;
	test -z $ORIGEMMATERIAL;
	if [ $? == 0 ]; then
	ORIGEMMATERIAL=${NULO};
	fi

    NUMERODOPROCESSO=${LINHA:416:20};
    NUMERODOPROCESSO=`echo "$NUMERODOPROCESSO" | sed "s/ //g"`;
	test -z $NUMERODOPROCESSO;
	if [ $? == 0 ]; then
	NUMERODOPROCESSO=${NULO};
	fi

    UFBENEFICIADA=${LINHA:436:2};
    UFBENEFICIADA=`echo "$UFBENEFICIADA" | sed "s/ //g"`;
	test -z $UFBENEFICIADA;
	if [ $? == 0 ]; then
	UFBENEFICIADA=${NULO};
	fi

    MUNICIPIOBENEFICIADO=${LINHA:438:4};
    MUNICIPIOBENEFICIADO=`echo "$MUNICIPIOBENEFICIADO" | sed "s/ //g"`;
	test -z $MUNICIPIOBENEFICIADO;
	if [ $? == 0 ]; then
	MUNICIPIOBENEFICIADO=${NULO};
	fi

    INCISO=${LINHA:442:2};
    INCISO=`echo "$INCISO" | sed "s/ //g"`;
	test -z $INCISO;
	if [ $? == 0 ]; then
	INCISO=${NULO};
	fi

    AMPAROLEGAL=${LINHA:444:8};
    AMPAROLEGAL=`echo "$AMPAROLEGAL" | sed "s/ //g"`;
	test -z $AMPAROLEGAL;
	if [ $? == 0 ]; then
	AMPAROLEGAL=${NULO};
	fi

    CODIGODAUGDODOCREFERENCIA=${LINHA:452:6};
    CODIGODAUGDODOCREFERENCIA=`echo "$CODIGODAUGDODOCREFERENCIA" | sed "s/ //g"`;
	test -z $CODIGODAUGDODOCREFERENCIA;
	if [ $? == 0 ]; then
	CODIGODAUGDODOCREFERENCIA=${NULO};
	fi

    CODIGODAGESTAODODOCREFERENCIA=${LINHA:458:5};
    CODIGODAGESTAODODOCREFERENCIA=`echo "$CODIGODAGESTAODODOCREFERENCIA" | sed "s/ //g"`;
	test -z $CODIGODAGESTAODODOCREFERENCIA;
	if [ $? == 0 ]; then
	CODIGODAGESTAODODOCREFERENCIA=${NULO};
	fi

    CONTROLEDEEMISSAO=${LINHA:463:1};
    CONTROLEDEEMISSAO=`echo "$CONTROLEDEEMISSAO" | sed "s/ //g"`;
	test -z $CONTROLEDEEMISSAO;
	if [ $? == 0 ]; then
	CONTROLEDEEMISSAO=${NULO};
	fi

    MESDELANCAMENTO=${LINHA:464:2};
    MESDELANCAMENTO=`echo "$MESDELANCAMENTO" | sed "s/ //g"`;
	test -z $MESDELANCAMENTO;
	if [ $? == 0 ]; then
	MESDELANCAMENTO=${NULO};
	fi

    SISTEMADEORIGEM=${LINHA:466:10};
    SISTEMADEORIGEM=`echo "$SISTEMADEORIGEM" | sed "s/ //g"`;
	test -z $SISTEMADEORIGEM;
	if [ $? == 0 ]; then
	SISTEMADEORIGEM=${NULO};
	fi

    INDENTIFICADORDENEDECONTRAENTREGA=${LINHA:476:1};
    INDENTIFICADORDENEDECONTRAENTREGA=`echo "$INDENTIFICADORDENEDECONTRAENTREGA" | sed "s/ //g"`;
	test -z $INDENTIFICADORDENEDECONTRAENTREGA;
	if [ $? == 0 ]; then
	INDENTIFICADORDENEDECONTRAENTREGA=${NULO};
	fi

    SITUACAODOCREDORNOSICAF=${LINHA:00477:2};
    SITUACAODOCREDORNOSICAF=`echo "$SITUACAODOCREDORNOSICAF" | sed "s/ //g"`;
	test -z $SITUACAODOCREDORNOSICAF;
	if [ $? == 0 ]; then
	SITUACAODOCREDORNOSICAF=${NULO};
	fi

    DATADEVENCIMENTO=${LINHA:479:288};
    DATADEVENCIMENTO=`echo "$DATADEVENCIMENTO" | sed "s/ //g"`;
	test -z $DATADEVENCIMENTO;
	if [ $? == 0 ]; then
	DATADEVENCIMENTO=${NULO};
	fi

    DATADEPAGAMENTO=${LINHA:767:288};
    DATADEPAGAMENTO=`echo "$DATADEPAGAMENTO" | sed "s/ //g"`;
	test -z $DATADEPAGAMENTO;
	if [ $? == 0 ]; then
	DATADEPAGAMENTO=${NULO};
	fi

    VALORCRONOGRAMADOOCORRE=${LINHA:1055:612};
    VALORCRONOGRAMADOOCORRE=`echo "$VALORCRONOGRAMADOOCORRE" | sed "s/ //g"`;
	test -z $VALORCRONOGRAMADOOCORRE;
	if [ $? == 0 ]; then
	VALORCRONOGRAMADOOCORRE=${NULO};
	fi

    ITNUORIGINAL=${LINHA:1667:20};
    ITNUORIGINAL=`echo "$ITNUORIGINAL" | sed "s/ //g"`;
	test -z $ITNUORIGINAL;
	if [ $? == 0 ]; then
	ITNUORIGINAL=${NULO};
	fi

    ITCOMSGDOCUMENTO=${LINHA:1687:3};
    ITCOMSGDOCUMENTO=`echo "$ITCOMSGDOCUMENTO" | sed "s/ //g"`;
	test -z $ITCOMSGDOCUMENTO;
	if [ $? == 0 ]; then
	ITCOMSGDOCUMENTO=${NULO};
	fi

    ITNUPRECATORIO=${LINHA:1690:20};
    ITNUPRECATORIO=`echo "$ITNUPRECATORIO" | sed "s/ //g"`;
	test -z $ITNUPRECATORIO;
	if [ $? == 0 ]; then
	ITNUPRECATORIO=${NULO};
	fi

    ITINPAGAMENTOPRECATORIO=${LINHA:1710:1};
    ITINPAGAMENTOPRECATORIO=`echo "$ITINPAGAMENTOPRECATORIO" | sed "s/ //g"`;
	test -z $ITINPAGAMENTOPRECATORIO;
	if [ $? == 0 ]; then
	ITINPAGAMENTOPRECATORIO=${NULO};
	fi

    ITNULISTA=${LINHA:1711:12};
    ITNULISTA=`echo "$ITNULISTA" | sed "s/ //g"`;
	test -z $ITNULISTA;
	if [ $? == 0 ]; then
	ITNULISTA=${NULO};
	fi

    ITINLIQUIDACAO=${LINHA:1723:1};
    ITINLIQUIDACAO=`echo "$ITINLIQUIDACAO" | sed "s/ //g"`;
	test -z $ITINLIQUIDACAO;
	if [ $? == 0 ]; then
	ITINLIQUIDACAO=${NULO};
	fi

    ITOPCAMBIAL=${LINHA:1724:10};
    ITOPCAMBIAL=`echo "$ITOPCAMBIAL" | sed "s/ //g"`;
	test -z $ITOPCAMBIAL;
	if [ $? == 0 ]; then
	ITOPCAMBIAL=${NULO};
	fi

    GSTCODFAVORECIDO=${LINHA:43:5};
    GSTCODFAVORECIDO=`echo "$GSTCODFAVORECIDO" | sed "s/ //g"`;
	test -z $GSTCODFAVORECIDO;
	if [ $? == 0 ]; then
	GSTCODFAVORECIDO=${NULO};
	fi

    UNGCODFAVORECIDO=${LINHA:37:6};
    UNGCODFAVORECIDO=`echo "$UNGCODFAVORECIDO" | sed "s/ //g"`;
	test -z $UNGCODFAVORECIDO;
	if [ $? == 0 ]; then
	UNGCODFAVORECIDO=${NULO};
	fi

    NOEANO=${LINHA:48:4};
    NOEANO=`echo "$NOEANO" | sed "s/ //g"`;
	test -z $NOEANO;
	if [ $? == 0 ]; then
	NOEANO=${NULO};
	fi

    NOENUM=${LINHA:54:6};
    NOENUM=`echo "$NOENUM" | sed "s/ //g"`;
	test -z $NOENUM;
	if [ $? == 0 ]; then
	NOENUM=${NULO};
	fi

    NOEDOCREFERENCIAANO=${LINHA:60:4};
    NOEDOCREFERENCIAANO=`echo "$NOEDOCREFERENCIAANO" | sed "s/ //g"`;
	test -z $NOEDOCREFERENCIAANO;
	if [ $? == 0 ]; then
	NOEDOCREFERENCIAANO=${NULO};
	fi

    NOEDOCREFERENCIA=${LINHA:66:6};
    NOEDOCREFERENCIA=`echo "$NOEDOCREFERENCIA" | sed "s/ //g"`;
	test -z $NOEDOCREFERENCIA;
	if [ $? == 0 ]; then
	NOEDOCREFERENCIA=${NULO};
	fi



    echo -e $CODIGODAUGDOOPERADOR${TAB}$PROGRAMADETRABALHORESUMIDOPTRES${TAB}$CODIGODAGESTAODODOCREFERENCIA${TAB}$NATUREZADEDESPESA${TAB}$GSTCODFAVORECIDO${TAB}$FONTEDERECURSO${TAB}$CODIGODOEVENTO${TAB}$ESFERAORCAMENTARIA${TAB}$CODIGODAUGRESPONSAVEL${TAB}$UNGCODFAVORECIDO${TAB}$CODIGODAUGDODOCREFERENCIA${TAB}$CODIGODAGESTAODODOCREFERENCIA${TAB}$NOEANO${TAB}$NOENUM${TAB}$DATADEVENCIMENTO${TAB}$DATADEEMISSAO${TAB}$DATADEPAGAMENTO${TAB}$DATADETRANSACAO${TAB}$DATADETRANSACAO${TAB}$VALORDATRANSACAO${TAB}$OBSERVACAO${TAB}$NUMERODOPROCESSO${TAB}$AMPAROLEGAL${TAB}$INCISO${TAB}$ITNUPRECATORIO${TAB}$ITINPAGAMENTOPRECATORIO${TAB}$ITNUORIGINAL${TAB}$ITNULISTA${TAB}$NOEDOCREFERENCIAANO${TAB}$NOEDOCREFERENCIA${TAB}$ITINLIQUIDACAO${TAB}$VALORCRONOGRAMADOOCORRE >> ../${FILE}.sql;

done
cd ..
mv ${FILE} ${LIDOS};
tar -cf ${LIDOS}${FILE}".tar.gz" ${LIDOS}${FILE}
rm ${LIDOS}${FILE}
mv ${FILE}.sql ${SQLCOPY}/${FILE}.sql;
rm ${LENDO}/${FILE};
psql -h $PGHOST -U $PGUSER -d $PGDB -f ${SQLCOPY}/${FILE}.sql
