<?php

define('PERFIL_EJA_SUPER_USUARIO', 1237);
define('PERFIL_EJA_DIRETOR_ESCOLA', 1238);
define('PERFIL_EJA_GESTOR', 1239);
define('PERFIL_EJA_CONSULTA', 1240);
define('PERFIL_EJA_GESTOR_ESTADUAL', 1241);
define('PERFIL_EJA_GESTOR_MUNICIPAL', 1242);
define('PERFIL_EJA_GESTOR_MEC', 1280);
define('DATA_ATUAL', date('Y/m/d'));
define('DATA_LIMITE', date('2015/08/17'));


?>
