<?PHP
# Mensagens de sistema
define('MSG001', 'Operação realizada com sucesso!');
define('MSG002', 'Operação não pode ser realizada!');

# Demandas PAR
if ($_SESSION['baselogin'] == 'simec_desenvolvimento') {

    define("DBLINK_PARAM_PDEINTERATIVO", 'dbname=
											hostaddr=
											user=
											password=
											port=');

    define('WF_TPDID_DEMANDA', 119);

    /*
     * INICIO de estados do documento da demanda
     * _____________________________________________________________________________
     */
    
    define("PAR_WF_DEMANDA_ESTADO_EM_CADASTRAMENTO", 778); # Envia para AGUARDANDO_ATENDIMENTO
    define("PAR_WF_DEMANDA_ESTADO_AGUARDANDO_ATENDIMENTO", 746); # Envia para ANALISE_DE_ATENDIMENTO
    define("PAR_WF_DEMANDA_ESTADO_EM_ANALISE_DE_ATENDIMENTO", 747); # Envia para ATENDIMENTO ou EM_DILIGENCIA
    define("PAR_WF_DEMANDA_ESTADO_EM_ATENDIMENTO", 749); # Envia para EM_DILIGENCIA ou EM_PAUSA ou AGUARDANDO_VALIDACAO
    define("PAR_WF_DEMANDA_ESTADO_EM_PAUSA", 752); # Volta para EM_ATENDIMENTO
    define("PAR_WF_DEMANDA_ESTADO_EM_DILIGENCIA", 748); # Volta para ANALISE_DE_ATENDIMENTO
    define("PAR_WF_DEMANDA_ESTADO_AGUARDANDO_VALIDACAO", 750); # Envia para ESTADO_CONCLUIDO
    define("PAR_WF_DEMANDA_ESTADO_CONCLUIDO", 751);# Nao pode mais fazer nada.
} else {
    if (IS_PRODUCAO) {
        define("DBLINK_PARAM_PDEINTERATIVO", 'dbname=
											hostaddr=
											user=
											password=
											port=');
    } else {
        define("DBLINK_PARAM_PDEINTERATIVO", 'dbname=
											hostaddr=
											user=
											password=
											port=');
    }
    define('WF_TPDID_DEMANDA', 127);

    /*
     * INICIO de estados do documento da demanda
     * _____________________________________________________________________________
     */

    define("PAR_WF_DEMANDA_ESTADO_EM_CADASTRAMENTO", 829);# Envia para AGUARDANDO_ATENDIMENTO
    define("PAR_WF_DEMANDA_ESTADO_AGUARDANDO_ATENDIMENTO", 830); # Envia para ANALISE_DE_ATENDIMENTO
    define("PAR_WF_DEMANDA_ESTADO_EM_ANALISE_DE_ATENDIMENTO", 831); # Envia para ATENDIMENTO ou EM_DILIGENCIA
    define("PAR_WF_DEMANDA_ESTADO_EM_DILIGENCIA", 832); # Volta para ANALISE_DE_ATENDIMENTO
    define("PAR_WF_DEMANDA_ESTADO_EM_ATENDIMENTO", 833); # Envia para EM_DILIGENCIA ou EM_PAUSA ou AGUARDANDO_VALIDACAO
    define("PAR_WF_DEMANDA_ESTADO_AGUARDANDO_VALIDACAO", 834); # Envia para ESTADO_CONCLUIDO
    define("PAR_WF_DEMANDA_ESTADO_CONCLUIDO", 835); # Nao pode mais fazer nada.
    define("PAR_WF_DEMANDA_ESTADO_EM_PAUSA", 836);# Volta para EM_ATENDIMENTO
}
/*
 * FIM de estados do documento da demanda
 * _____________________________________________________________________________
 */

define("SISID_PAR", 23);

#Termo de Compromisso
define("TIPO_TERMO", 1);

# TIPOS DE IMPRESSÃO DO TERMO
define("TIPO_IMPRESSAO_TERMO_REGERAR", 1);

# Intrumento diagnóstico
define("INSTRUMENTO_DIAGNOSTICO_ESTADUAL", 1);
define("INSTRUMENTO_DIAGNOSTICO_MUNICIPAL", 2);
define("STATUS_SUBACAO_EM_REFORMULACAO", 20);
define("STATUS_SUBACAO_EM_DILIGENCIA_REPROGRAMACAO", 23);

/*
 * PERFIS
 */
define("PAR_PERFIL_SUPER_USUARIO", 441);
define("PAR_PERFIL_CONTROLE_USUARIO", 1416 );
define("PAR_PERFIL_NUTRICIONISTA", 1374);
define("PAR_PERFIL_ADMINISTRADOR", 459);
if ($_SESSION['baselogin'] == 'simec_desenvolvimento') {
    define("PAR_PERFIL_DEMANDANTE_PAR", 938);
} else {
    define("PAR_PERFIL_DEMANDANTE_PAR", 1012);
}
define("PAR_PERFIL_EQUIPE_FINANCEIRA", 458);
define("PAR_PERFIL_EQUIPE_MUNICIPAL", 460);
define("PAR_PERFIL_EQUIPE_MUNICIPAL_APROVACAO", 674);
define("PAR_PERFIL_PREFEITO", 556);
define("PAR_PERFIL_EQUIPE_ESTADUAL", 461);
define("PAR_PERFIL_EQUIPE_ESTADUAL_APROVACAO", 672);
define("PAR_PERFIL_EQUIPE_ESTADUAL_SECRETARIO", 673);
define("PAR_PERFIL_EQUIPE_TECNICA", 457);
define("PAR_PERFIL_ENGENHEIRO_FNDE", 468); # Analista Técnico de Obras - FNDE
define("PAR_PERFIL_COORDENADOR_GERAL", 477); # Coordenador Técnico de Obras - FNDE
define("PAR_PERFIL_COORDENADOR_TECNICO", 478);
define("PAR_PERFIL_CONSULTA", 484);
define("PAR_PERFIL_CONSULTA_ESTADUAL", 488);
define("PAR_PERFIL_CONSULTA_MUNICIPAL", 489);
define("PAR_PERFIL_CONTROLE_SOCIAL_ESTADUAL", 1415);
define("PAR_PERFIL_CONTROLE_SOCIAL_MUNICIPAL", 1414);
define("PAR_PERFIL_ANALISE_PI", 587);
define("PAR_PERFIL_PROFUNC_PREANALISEPF", 539);
define("PAR_PERFIL_PROFUNC_ANALISEPF", 540);
define("PAR_PERFIL_PROFUNC_PREANALISEPF_TUTOR", 546);
define("PAR_PERFIL_PROFUNC_ANALISEPF_TUTOR", 548);
define("PAR_PERFIL_MANUTENCAO_TABELAS_APOIO", 545);
define("PAR_PERFIL_PAGADOR", 669);
define("PAR_PERFIL_ANALISTA_MERITOS", 689);
define("PAR_PERFIL_ANALISTA_QUESTOES_PONTUAIS", 685);
define("PAR_PERFIL_EMPENHADOR", 670);
define("PAR_PERFIL_GERADOR_DOCUMENTO", 671);
define("PAR_PERFIL_ALTA_GESTAO_MEC", 706);
define("PAR_PERFIL_ADMINISTRADOR_PROCESSOS", 805);
define("PAR_PERFIL_UNIVERSIDADE_ESTADUAL", 853);
define("PAR_PERFIL_PARLAMENTAR", 876);
define("PAR_PERFIL_ORGAO_CONTROLE", 877);
define("PAR_PERFIL_ADM_OBRAS", 882);
//define("PAR_PERFIL_SECRETARIO_ESTADUAL_EDUCACAO",	884);
define("PAR_PERFIL_SECRETARIO_ESTADUAL_EDUCACAO", 672);
define("PAR_PERFIL_SECRETARIO_ESTADUAL_SAUDE", 887);
define("PAR_PERFIL_ORGAO_DE_CONTROLE", 1094);
define("PAR_PERFIL_ENTIDADE_EXECUTORA", 1141);
define("PAR_PERFIL_ANALISTA_TR", 1194);
define("PAR_PERFIL_ADMINISTRADOR_REPROGRAMAÇÃO", 1224);
define("GRUPO_DE_PERFIL_MUNICIPAL_EDICAO", serialize(ARRAY(PAR_PERFIL_EQUIPE_MUNICIPAL, PAR_PERFIL_EQUIPE_MUNICIPAL_APROVACAO, PAR_PERFIL_PREFEITO)));
define("GRUPO_DE_PERFIL_ESTADUAL_EDICAO", serialize(ARRAY(PAR_PERFIL_EQUIPE_ESTADUAL, PAR_PERFIL_EQUIPE_ESTADUAL_APROVACAO, PAR_PERFIL_EQUIPE_ESTADUAL_SECRETARIO)));

define("GRUPO_DE_PERFIL_ESTADUAL", serialize(ARRAY(
PAR_PERFIL_PREFEITO, 
PAR_PERFIL_EQUIPE_ESTADUAL_BRASIL_PRO,
PAR_PERFIL_EQUIPE_ESTADUAL_APROVACAO_BRASIL_PRO,
PAR_PERFIL_EQUIPE_ESTADUAL_APROVACAO,
PAR_PERFIL_EQUIPE_ESTADUAL,
PAR_PERFIL_CONSULTA_ESTADUAL,
PAR_PERFIL_CONTROLE_SOCIAL_ESTADUAL,
PAR_PERFIL_SECRETARIO_ESTADUAL_EDUCACAO)));

define("GRUPO_DE_PERFIL_MUNICIPAL", serialize(ARRAY(
PAR_PERFIL_EQUIPE_MUNICIPAL, 
PAR_PERFIL_CONSULTA_MUNICIPAL,
PAR_PERFIL_CONTROLE_SOCIAL_MUNICIPAL,
PAR_PERFIL_EQUIPE_MUNICIPAL_APROVACAO)));

# PERFIS BRASIL PRO
define("PAR_PERFIL_EQUIPE_ESTADUAL_BRASIL_PRO", 838);
define("PAR_PERFIL_EQUIPE_ESTADUAL_APROVACAO_BRASIL_PRO", 839);

# PERFIL EJA
define("PAR_PERFIL_ANALISTA_EJA", 1080);

# PERFIL MAIS MÉDICOS.
define("PAR_PERFIL_AVAL_INSTITUCIONAL_MM", 1153);

# Tipo de dados da unidade
define("GOVERNO_ESTADUAL_MUNICIPAL", 1);
define("DIRIGENTE_ESTADUAL_MUNICIPAL", 2);
define("EQUIPE_LOCAL", 3);
define("COMITE_LOCAL_INTEGRANTES", 4);
define("COMITE_LOCAL_COORDENADOR", 5);

define("ALIMENTACAO_ESCOLAR_TECNICO_NUTRICIONISTA", 11);
define("ALIMENTACAO_ESCOLAR_NUTRICIONISTA", 12);



# Forma de execução proposta subação do guia
define("FORMA_EXECUCAO_ACAO_PAC", 1);
define("FORMA_EXECUCAO_ASSITENCIA_TECNICA", 2);
define("FORMA_EXECUCAO_TRANSFERENCIA_VOLUNTARIA", 3);
define("FORMA_EXECUCAO_EXECUTADA_PELO_MUNICIPIO", 4);
define("FORMA_EXECUCAO_FINANCIAMENTO_BNDES", 5);
define("FORMA_EXECUCAO_ASSISTENCIA_FINANCEIRA", 6);
define("FORMA_EXECUCAO_ASSISTENCIA_FINANCEIRA_OBRAS", 11);
define("FORMA_EXECUCAO_EXECUTADA_PELO_ESTADO", 12);
define("ASSISTENCIA_FINANCEIRA_EXTRAORDINARIA", 13);
define("ASSISTENCIA_FINANCEIRA_EMENDA", 14);
define("ASSISTENCIA_FINANCEIRA_EMENDA_OBRAS", 15);
define("ASSISTENCIA_FINANCEIRA_BRASIL_PRO", 16);
define("ASSISTENCIA_FINANCEIRA_BRASIL_PRO_OBRAS", 17);
define("ASSISTENCIA_FINANCEIRA_MOB_EQUIPE_PROINFANCIA", 18);

# Fase do Workflow
define("ELABORACAO", 451);
define("ANALISE", 452);
define("GERACAO_TERMO_COOPERACAO", 453);
define("DILIGENCIA", 454);
define("AGUARDANDO_ANALISE_GESTOR", 455);
define("EMPENHO", 456);
define("PAGAMENTO", 457);
define("INDEFERIDA", 458);
define("EM_ANALISE_COMISSAO", 462);

# Filtros de Subações para Lista Agrupada
define("SUBACOES_ANALISADAS", 1);
define("SUBACOES_PENDENTESDEANALISE", 2);
define("SUBACOES_GERADOTERMO", 3);
define("SUBACOES_CONVENIADA", 4);
define("SUBACOES_COMITENS", 5);
define("SUBACOES_SEMITENS", 6);
define("SUBACOES_COM_OBRAS", 7);

# Tipo de Subação
define("FORMA_EXECUCAO_EXECUTADA_PELO_MUNICIPIO_SEM_ITENS", 42);
define("FORMA_EXECUCAO_EXECUTADA_PELO_MUNICIPIO_COM_ITENS", 43);
define("FORMA_EXECUCAO_EXECUTADA_PELO_ESTADO_SEM_ITENS", 46);
define("FORMA_EXECUCAO_EXECUTADA_PELO_ESTADO_COM_ITENS", 45);
define("FORMA_EXECUCAO_ASSISTENCIA_FINANCEIRA_OBRAS_AMPLIACAO_ESCOLAS", 17);
define("FORMA_EXECUCAO_ASSISTENCIA_FINANCEIRA_OBRAS_REFORMA_ESCOLAS", 16);
define("FORMA_EXECUCAO_ASSISTENCIA_FINANCEIRA_OBRAS_CONSTRUCAO_ESCOLAS", 15);
define("FORMA_EXECUCAO_ASSISTENCIA_FINANCEIRA_BRASIL_PRO_COM_ITENS", 61);
define("FORMA_EXECUCAO_ASSISTENCIA_FINANCEIRA_BRASIL_PRO_FORMACAO", 81);
define("FORMA_EXECUCAO_ASSISTENCIA_FINANCEIRA_BRASIL_PRO_SEM_ITENS", 62);

# Tipo de obra da subação PTOID
define("OBRA_TIPO_A", 1);
define("OBRA_TIPO_B", 2);
define("OBRA_TIPO_C", 3);
define("OBRA_QUADRA_COBERTURA", 5);
define("OBRA_TIPO_C_220v", 6);
define("OBRA_TIPO_B_220v", 7);
define("OBRA_QUADRA_COBERTA_PROJETO_PROPRIO", 9);
define("OBRA_COBERTURA_PEQUENA", 23);
define("OBRA_COBERTURA_GRANDE", 28);
define("OBRA_COBERTURA_VESTIARIO", 27);
define("OBRA_TIPO_B_NOVO", 38);
define("OBRA_TIPO_C_NOVO", 39);
define("OBRA_TIPO_ESCOLA_PROINFANCIA_B_MI", 43);
define("OBRA_TIPO_ESCOLA_PROINFANCIA_C_MI", 42);
define("OBRA_TIPO_ESCOLA_PROINFANCIA_B_MI_EMENDA", 44);
define("OBRA_TIPO_ESCOLA_PROINFANCIA_C_MI_EMENDA", 45);
define("OBRA_TIPO_ESCOLA_INFANTIL_TIPO_B_CONVENCIONAL_PAC", 73);
define("OBRA_TIPO_ESCOLA_INFANTIL_TIPO_B_CONVENCIONAL_PAR", 74);
define("OBRA_TIPO_ESCOLA_INFANTIL_TIPO_C_CONVENCIONAL_PAC", 75);
define("OBRA_TIPO_ESCOLA_INFANTIL_TIPO_C_CONVENCIONAL_PAR", 76);
// define("OBRA_TIPO_MI_TIPO_B_PROJETO_PROPRIO_PAC", 77);
// define("OBRA_TIPO_MI_TIPO_B_PROJETO_PROPRIO_PAR", 78);
// define("OBRA_TIPO_MI_TIPO_C_PROJETO_PROPRIO_PAC", 79);
// define("OBRA_TIPO_MI_TIPO_B_PROJETO_PROPRIO_PAR", 80);

# Workflow tipo documento
/*
  define("WF_FLUXO_PRO_INFANCIA", 	24);
  define("WF_TIPO_EM_CADASTRAMENTO", 	190);
  define("WF_TIPO_EM_ANALISE_FNDE", 	191);
  define("WF_TIPO_EM_CORRECAO", 		192);
 */

#FLUXO DOS PROGRAMAS EJA/EJA PRONATEC
define("WF_FLUXO_EJA_PRONATEC", 162);
define("WF_FLUXO_EJA_FINANCIA", 84);
define("WF_FLUXO_PRO_INFANCIA", 37);
define("WF_FLUXO_PRONATEC", 47);
define("WF_FLUXO_PROGRAMAS_FORMACAO", 41);
define("WF_FLUXO_OBRAS_PAR", 45);
define("WF_FLUXO_PRO_TRANSPORTE", 59);
define("WF_FLUXO_PRO_AGUA_ESCOLA", 77);

# PROINFANCIA
define("WF_TIPO_EM_CADASTRAMENTO", 193);
define("WF_TIPO_EM_ANALISE_FNDE", 194);
define("WF_TIPO_EM_CORRECAO", 195);
define("WF_TIPO_EM_REFORMULACAO", 360);
define("WF_TIPO_EM_REFORMULACAO_OBRAS_MI", 683);
define("WF_TIPO_ANALISE_DE_REFORMULACAO_OBRAS_MI", 754);
define("WF_TIPO_EM_REFORMULACAO_MI_PARA_CONVENCIONAL", 1486);
define("WF_TIPO_EM_DILIGENCIA_REFORMULACAO_MI_PARA_CONVENCIONAL", 1548);
define("WF_TIPO_EM_DILIGENCIA_SOLICITACAO_REFORMULACAO_MI_PARA_CONVENCIONAL", 1578);
define("WF_TIPO_EM_ANALISE_REFORMULACAO_MI_PARA_CONVENCIONAL", 1487);
define("WF_TIPO_EM_ANALISE_REFORMULACAO_MI_PARA_CONVENCIONAL_RETORNO_DILIGENCIA", 1564);
define("WF_TIPO_EM_VALIDACAO_DEFERIMENTO_REFORMULACAO_MI_PARA_CONVENCIONAL", 1553);
define("WF_TIPO_EM_AGUARDANDO_VALIDACAO_REFORMULACAO_MI_PARA_CONVENCIONAL", 1561);
define("WF_TIPO_EM_ANALISE_SOLICITACAO_REFORMULACAO_MI_PARA_CONVENCIONAL_RETORNO_DILIGENCIA", 1579);
define("WF_TIPO_EM_VALIDACAO_GESTOR_MI_PARA_CONVENCIONAL", 1550); 
define("WF_TIPO_EM_ANALISE_REFORMULACAO", 365);
define("WF_TIPO_EM_VALIDACAO_INDEFERIMENTO_REFORMULACAO", 366);
define("WF_TIPO_EM_VALIDACAO_DEFERIMENTO_REFORMULACAO", 367);

# Programa Transporte Escolar Acessivel
define("WF_PRO_TRANSPORTE_EM_CADASTRAMENTO", 426);
define("WF_PRO_TRANSPORTE_EM_DILIGENCIA", 428);

# Programa Água na Escola
define("WF_TIPO_AGUANAESCOLA_EM_CADASTRAMENTO", 530);
define("WF_TIPO_VALIDACAO_DILIGENCIA", 210);
define("WF_TIPO_VALIDACAO_INDEFERIMENTO", 211);
define("WF_TIPO_VALIDACAO_DEFERIMENTO", 212);
define("WF_TIPO_OBRA_INDEFERIDA", 213);
define("WF_TIPO_OBRA_DEFERIDA", 214);
define("WF_TIPO_EM_ANALISE", 215);
define("WF_TIPO_EM_ANALISE_VALIDACAO", 217);
define("WF_TIPO_EM_ANALISE_DILIGENCIA", 218);

# escolheu nao
define("WF_AEDID_ANALISE_FNDE_ENVIAR_VALIDACAO_INDEFERIMENTO", 514);
# escolheu sim
define("WF_AEDID_ANALISE_FNDE_ENVIAR_PARA_ANALISE", 515);

define("WF_AEDID_OBRA_APROVADA_ENVIAR_PARA_AGUARDANDO_PRORROGACAO", 1774);
define("WF_AEDID_AGUARDANDO_PRORROGACAO_ENVIAR_PARA_OBRA_APROVADA", 1775);

# PRONATEC
define("WF_PRONATEC_EM_CADASTRAMENTO", 347);
define("WF_PRONATEC_EM_ANALISE_FNDE", 348);
define("WF_PRONATEC_EM_ANALISE", 357);
define("WF_PRONATEC_EM_DILIGENCIA", 349);
define("WF_PRONATEC_VALIDACAO_DILIGENCIA", 345);
define("WF_PRONATEC_VALIDACAO_INDEFERIMENTO", 346);
define("WF_PRONATEC_VALIDACAO_DEFERIMENTO", 350);
define("WF_PRONATEC_OBRA_INDEFERIDA", 353);
define("WF_PRONATEC_OBRA_DEFERIDA", 354);
define("WF_PRONATEC_EM_REVISAO_DE_ANALISE", 351);
define("WF_PRONATEC_EM_ANALISE_RETORNO_DA_DILIGENCIA", 352);
define("WF_PRONATEC_OBRA_CONDICIONADA", 355);
define("WF_PRONATEC_OBRA_INDEFERIDA_PRAZO", 356);
define("WF_PRONATEC_OBRA_APROVADA", 358);
define("WF_PRONATEC_OBRA_ARQUIVADA", 359);

# escolheu nao
define("WF_PRONATEC_AEDID_ANALISE_FNDE_ENVIAR_VALIDACAO_INDEFERIMENTO", 913);
# escolheu sim
define("WF_PRONATEC_AEDID_ANALISE_FNDE_ENVIAR_PARA_ANALISE", 912);

# Contantes para montar a tabela de execução do PAR
define('TIPO_PAR', 1);
define('TIPO_OBRAS_PAR', 2);
define('TIPO_OBRAS_PAC', 3);

# Constantes Obras2 
define("TPDID_OBJETO", 105);
define("OBR_ESDID_AGUARDANDO_1_REPASSE", 762);
define("OBR_ESDID_AGUARDANDO_ADESAO_DO_MUNICIPIO", 884);
define("OBR_ESDID_EM_EXECUCAO", 690);
define("OBR_ESDID_PARALISADA", 691);
define("OBR_ESDID_CONCLUIDA", 693);
define("OBR_ESDID_EM_ELABORACAO_DE_PROJETOS", 689);
define("OBR_ESDID_EM_LICITACAO", 763);
define("OBR_ESDID_CONTRATO_CANCELADO", 766);
define("OBR_ESDID_CONVENIO_CANCELADO", 767);
define("OBR_ESDID_EM_REFORMULACAO", 768);
define("OBR_ESDID_OBRA_CANCELADA", 769);
define("OBR_ESDID_ETAPA_CONCLUIDA", 770);
define("OBR_ESDID_AGUARDANDO_REGISTRO_DE_PRECOS", 771);
define("OBR_ESDID_EM_PLANEJAMENTO_PELO_PROPONENTE", 689);

# OBRAS PAC
define("WF_TPDID_FLUXO_OBRA_PAC", 37);
define("WF_TIPO_OBRA_CONDICIONADA", 220);
define("WF_TIPO_OBRA_INDEFERIDA_PRAZO", 221);
define("WF_TIPO_OBRA_APROVADA", 228);
define("WF_TIPO_OBRA_ARQUIVADA", 229);
define("WF_TIPO_OBRA_AGUARDANDO_PRORROGACAO", 755);
define("WF_TIPO_OBRA_APROVACAO_CONDICIONAL", 889);
define("WF_TIPO_PROFUNC_CADASTRAMENTO", 289);
define("WF_TIPO_PROFUNC_PREANALISE", 294); 
define("WF_TIPO_PROFUNC_ANALISE", 295);
define("WF_TIPO_PROFUNC_MATRICULA", 296);
define("WF_TIPO_PNAIC_CADASTRAMENTO", 483);
define("WF_TIPO_PNAIC_PREANALISE", 484);
define("WF_TIPO_PNAIC_ANALISE", 485);
define("WF_TIPO_PNAIC_MATRICULA", 489);
define("WF_TIPO_OBRA_PRORROGACAO_CANCELADA", 1435); //PRODUCAO - 1435

# OBRAS PAR
define("WF_PAR_EM_CADASTRAMENTO", 326);
define("WF_PAR_EM_ANALISE_FNDE", 327);
define("WF_PAR_EM_ANALISE", 336);
define("WF_PAR_EM_DILIGENCIA", 328);
define("WF_PAR_VALIDACAO_DILIGENCIA", 324);
define("WF_PAR_VALIDACAO_INDEFERIMENTO", 325);
define("WF_PAR_VALIDACAO_DEFERIMENTO", 329);
define("WF_PAR_OBRA_INDEFERIDA", 332);
define("WF_PAR_OBRA_DEFERIDA", 333);
define("WF_PAR_EM_REVISAO_DE_ANALISE", 330);
define("WF_PAR_EM_ANALISE_RETORNO_DA_DILIGENCIA", 331);
define("WF_PAR_OBRA_CONDICIONADA", 334);
define("WF_PAR_OBRA_INDEFERIDA_PRAZO", 335);
define("WF_PAR_OBRA_APROVADA", 337);
define("WF_PAR_OBRA_ARQUIVADA", 338);
define("WF_PAR_OBRA_VAL_INDEF_REFORMULACAO", 366);
define("WF_PAR_OBRA_EM_REFORMULACAO", 624);
define("WF_PAR_OBRA_APROVACAO_SOLICITACAO_REFORMULACAO_MI_PARA_CONVENCIONAL", 1561);
define("WF_PAR_OBRA_EM_REFORMULACAO_MI_CONVENCIONAL", 1488);
define("WF_PAR_OBRA_EM_ANALISE_REFORMULAÇÃO", 625);
define("WF_PAR_OBRA_EM_ANALISE_REFORMULACAO_MI_CONVENCIONAL", 1489);
define("WF_PAR_OBRA_EM_ANALISE_REFORMULACAO_MI_CONVENCIONAL_RETORNO_DILIGENCIA", 1568);
define("WF_PAR_OBRA_EM_VALIDACAO_INDEFERIMENTO_REFORMULACAO", 626);
define("WF_PAR_OBRA_EM_VALIDACAO_DEFERIMENTO_REFORMULACAO", 627);
define("WF_PAR_OBRA_CANCELADA", 628);
define("WF_AEDID_OBRA_PAR_APROVADO_ENVIAR_EM_REFORMULACAO", 1581);
define("WF_AEDID_OBRA_PAR_APROVADO_ENVIAR_EM_REFORMULACAO_MI", 1770);
define("WF_AEDID_OBRA_PAR_CANCELA_REFORMULACAO", 1583);
define("WF_PAR_OBRA_EM_CADASTRAMENTO_CONDICIONAL", 827);
define("WF_PAR_OBRA_EM_APROVACAO_CONDICIONAL", 825);
define("WF_PAR_OBRA_AGUARDANDO_PRORROGACAO", 1260);
define("WF_AEDID_PAR_AGUARDANDO_PRORROGACAO_ENVIAR_PARA_OBRA_APROVADA", 2902); 
define("WF_AEDID_PAR_AGUARDANDO_PRORROGACAO_ENVIAR_PARA_OBRA_RECUSADA", 3055); 
define("WF_PAR_PRORROGACAO_CANCELADA", 1436); //PRODUCAO - 1436
define("WF_TIPO_EM_REFORMULACAO_MI_PARA_CONVENCIONAL_PAR", 1488);
define("WF_TIPO_EM_DILIGENCIA_REFORMULACAO_MI_PARA_CONVENCIONAL_PAR", 1549);
define("WF_TIPO_EM_ANALISE_REFORMULACAO_MI_PARA_CONVENCIONAL_PAR", 1489);
define("WF_TIPO_EM_VALIDACAO_DEFERIMENTO_REFORMULACAO_MI_PARA_CONVENCIONAL_PAR", 1566);
define("WF_TIPO_EM_VALIDACAO_GESTOR_MI_PARA_CONVENCIONAL_PAR", 1551);

# Ações OBRAS PAR
define("OBRA_AEDID_ENVIAR_PARA_REFORMULACAO_MI", 1772);
define("OBRA_AEDID_RETORNAR_PARA_EM_REFORMULACAO_MI", 1950);

# Tipo de OBRAS PAR
define("OBRA_PROJETO_PROPRIO", 16);

# PNAIC
define("WF_TIPO_PNAIC_CADASTRAMENTO", 483);

# Pergunta indeferimento
define("QUEST_PAR_INDEFERIMENTO", 2700);

# escolheu nao
define("WF_PAR_AEDID_ANALISE_FNDE_ENVIAR_VALIDACAO_INDEFERIMENTO", 858);
# escolheu sim

define("WF_PAR_AEDID_ANALISE_FNDE_ENVIAR_PARA_ANALISE", 859);
define("WF_AEDID_ANALISE_ENVIAR_VALIDACAO_DILIGENCIA", 522);
define("WF_AEDID_ANALISE_ENVIAR_VALIDACAO_DEFERIMENTO", 523);
define("WF_AEDID_ANALISE_ENVIAR_VALIDACAO_INDEFERIMENTO", 524);

define("WF_AEDID_APROVADO_ENVIAR_EM_REFORMULACAO", 976);

# Sistemas relacionados
define("SIS_OBRAS", 23);

# Grupos
define("TIPOMUN_GRUPO1", 150);
define("TIPOMUN_GRUPO2", 151);
define("TIPOMUN_GRUPO3", 152);

# novos grupos
define("TIPOMUN_GRUPO1_2011", 163);
define("TIPOMUN_GRUPO2_2011", 164);
define("TIPOMUN_GRUPO3_2011", 165);
/*
  define("SIS_OBRAS", 15);
 */

#PROGRAMAS ACESSADOS PELO PAR - DISPONIVEIS PARA ADESAO.
define("PROGRAMA_PROFUNCIONARIO", 1);
define("PROGRAMA_ESCOLA_GESTORES", 2);
define("PROGRAMA_PROINFANTIL", 3);
define("PROGRAMA_PRADIME", 4);
# define("PROGRAMA_ONIBUS_ACESSIVEL", 5); #Programa 2012
define("PROGRAMA_ONIBUS_ACESSIVEL", 11); #Programa 2013
define("PROGRAMA_PROCONSELHO", 6);
define("PROGRAMA_ALFABETIZACAO_IDADE_CERTA", 8);
define("PROGRAMA_AGUANAESCOLA", 9);

#PROGRAMA DE ADESÃO - ID.
define("PROGRAMA_EJA", 19);
define("PROGRAMA_CONSELHO_ESCOLAR", 13);
define("PROGRAMA_CORREPULA", 12);
define("PROGRAMA_PSE", 14);
define("PROGRAMA_EMI", 16);
define("PROGRAMA_ALFABETIZACAO_ENSINO_MEDIO", 18);
define("PROGRAMA_ESCOLA_TERRA", 15);
define("PROGRAMA_ATLETA2014", 20);
define("PROGRAMA_EJA_PRONATEC", 22);
define("PROGRAMA_ESCOLANACOPA", 24);
define("PROGRAMA_INSTRUTOR_CONSELHO_ESCOLAR", 25);

#PROGRAMAS ACESSADOS PELO PAR - TABELA PROGRAMAS.
define("PROG_PAR_PROFUNCIONARIO", 60);
define("PROG_PAR_ESCOLA_GESTORES", 12);
define("PROG_PAR_PROINFANTIL", 121);
define("PROG_PAR_PRADIME", 9);
define("PROG_PAR_ONIBUS_ACESSIVEL", 153);
define("PROG_PAR_PROCONSELHO", 155);
define("PROG_PAR_ALFABETIZACAO_IDADE_CERTA", 157);
define("PROG_PAR_AGUANAESCOLA", 183);
define("PROG_PAR_EJA", 188);
define("PROG_PAR_CONSELHO_ESCOLAR", 4);
define("PROG_PAR_CORREPULA", 218);
define("PROG_PAR_PSE", 219);
define("PROG_PAR_EMI", 220);
define("PROG_PAR_ALFABETIZACAO_ENSINO_MEDIO", 221);
define("PROG_PAR_ESCOLA_TERRA", 224);
define("PROG_PAR_MAIS_MEDICOS", 228);
define("PROG_PAR_ATLETA2014", 218);
define("PROG_PAR_ESCOLANACOPA", 248);
define("PROG_PAR_INSTRUTOR_CONSELHO_ESCOLAR", 247);

# Pró Funcionario
if ($_SESSION['baselogin'] == 'simec_desenvolvimento') {
    define("QUESTIONARIOPROMUN", 101); # municipal
    define("QUESTIONARIOPROEST", 102); # estadual
    define("PERGUNTA_1", 1729);
    define("PERGUNTA_2", 1720);
    if ($_SESSION['par']['itrid'] == 1) {
        define("RESPOSTA1_BLOQUEIA_PROFUN", 3197);
    } else {
        define("RESPOSTA1_BLOQUEIA_PROFUN", 3162);
    }
    define("FUNID_PROFESSOR_TUTOR", 84);
    define("FUNID_COORDENADOR_PROFUN", 83);
} else {
    define("QUESTIONARIOPROMUN", 59); # municipal
    define("QUESTIONARIOPROEST", 60); # estadual
    define("PERGUNTA_1", 1567);
    define("PERGUNTA_2", 1558);
    if ($_SESSION['par']['itrid'] == 1) {
        define("RESPOSTA1_BLOQUEIA_PROFUN", 3026);
    } else {
        define("RESPOSTA1_BLOQUEIA_PROFUN", 3012);
    }
    define("FUNID_PROFESSOR_TUTOR", 88);
    define("FUNID_COORDENADOR_PROFUN", 87);
}

# Plano de Apoio
define("NENHUMA_MODALIDADE", 7);

# Datas das travas do Pró Infância
define("DATA_EXPIRA_PROINFANCIA", "20101030000000");
# define("DATA_EXPIRA_PROINFANCIA_PENDENCIAS", "20103012170000");
define("DATA_EXPIRA_PROINFANCIA_PENDENCIAS2", "20110131235959");
define("DATA_EXPIRA_PROINFANCIA_PENDENCIAS", "20110114235959");
define("DATA_EXPIRA_PROINFANCIA_PENDENCIAS_G_1_e_2", "20120211235959");
define("DATA_EXPIRA_PROINFANCIA_PENDENCIAS_G_3", "20120415235959");

# Questões Analise
define("QUESTAO_DOCUMENTO1", 1299);
define("QUESTAO_DOCUMENTO2", 1301);
define("QUESTAO_FOTOS", 1303);
define("QUESTAO_PLANILHA", 1305);
define("QUESTAO_CRONOGRAMA", 1307);
define("QUESTAO_ESTUDO_DEM", 1309);
define("QUESTAO_PLANILHA_LOCALIZACAO", 1311);
define("QUESTAO_PLANILHA_SIT", 1313);
define("QUESTAO_PLANILHA_LOCACAO", 1315);
define("QUESTAO_PLANIALTIMETRICO", 1317);
define("QUESTAO_DOMINIALLIDADE", 1319);
define("QUESTAO_FORNECIMENTO_INFRA", 1321);
define("QUESTAO_COMPATIBILIDADE_FUNDACAO", 1322);

# Função entidades
define("FUNID_PREFEITURA", 1);
define("FUNID_PREFEITO", 2);
define("FUNID_ESCOLA", 3);
define("FUNID_SECRETARIA_MUNICIPAL_EDUCACAO", 7);
define("FUNID_SECRETARIA_ESTADUAL_EDUCACAO", 6);
define("FUNID_DIRIGENTE_MUNICIPAL_EDUCACAO", 15);
define("FUNID_SECRETARIO_ESTADUAL_EDUCACAO", 25);

# Tipo de Dados da Unidade
define("DUTID_DIRIGENTE", 2);
define("DUTID_EQUIPE_LOCAL", 3);
define("DUTID_COMITE_INTEGRANTES", 4);
define("DUTID_COMITE_COORDENADOR", 5);
define("DUTID_PREFEITURA", 6);
define("DUTID_PREFEITO", 7);
define("DUTID_SECRETARIA_MUNICIPAL", 8);
define("DUTID_SECRETARIA_ESTADUAL", 9);
define("DUTID_SECRETARIO_ESTADUAL", 10);

if ($_SESSION['baselogin'] == 'simec_desenvolvimento') {
    define("FUNID_COORDENADOR_PRO_FUNCIONARIO", 83);
    define("FUNID_PROF_TUTOR_PRO_FUNCIONARIO", 84);
    define("FUNID_CURSISTA_PROGRAMA_FORMACAO", 85);
} else {
    define("FUNID_COORDENADOR_PRO_FUNCIONARIO", 87);
    define("FUNID_PROF_TUTOR_PRO_FUNCIONARIO", 88);
    define("FUNID_CURSISTA_PROGRAMA_FORMACAO", 89);
}

# Cursos pro infância
define("CURSO_FORMACAO_PEDAGOGICA", 5);

# Datas
define("DATA_DADOS_UNIDADE_ATUALIZA", '2011-02-15');

if ($_SESSION['baselogin'] == 'simec_desenvolvimento') {
    define("QUESTOES_PONTUAIS_QUEID", '41');
    define("QUESTOES_PONTUAIS_ESCOLAS", '935');
} else {
    define("QUESTOES_PONTUAIS_QUEID", '58');
    define("QUESTOES_PONTUAIS_ESCOLAS", '1528');
}

if ($_SESSION['baselogin'] == 'simec_desenvolvimento' || $_SESSION['baselogin'] == 'simec_espelho_producao') {
    define("USUARIO_SIGARP", 'MECVICTOR');
    define("SENHA_SIGARP", '27672463');
} else {
    define("USUARIO_SIGARP", 'USAP_WS_SIGARP');
    # define("SENHA_SIGARP", '97635212');
    // define("SENHA_SIGARP", '28241625'); // SEnha antiga modificada em 13/10 a pedido do Daniel e Murilo
    define("SENHA_SIGARP", '03422625');
}

# ID da licitação para as Obras MI
define("LICITACAO_MI", 23640);

# Origem da Pré-Obra
define("ORIGEM_OBRA_PAC2", 1);
define("ORIGEM_OBRA_PAR", 2);
define("ORIGEM_OBRA_PRONATEC", 3);
define("ORIGEM_OBRA_EMENDAS", 4);

# Exceções par
define("EXCECAO", 43);

/* * ** WORKFLOW PAR 2010 *** */
define("WF_DIAGNOSTICO", 313);
define("WF_ELABORACAO", 314);
define("WF_ANALISE", 315);

/* * ** TPDID DAS SUBACOES DO PAR *** */
define("WF_TPDID_SUBACOES_PAR", 62);

/* * ** WORKFLOW DAS SUBACAOES DO PAR *** */
define("WF_SUBACAO_ELABORACAO", 451);
define("WF_SUBACAO_ANALISE", 452);
define("WF_SUBACAO_GERACAO_TERMO_COOP", 453);
define("WF_SUBACAO_DILIGENCIA", 454);
define("WF_SUBACAO_APROVACAO_CONDICIONAL", 828);
define("WF_SUBACAO_DILIGENCIA_CONDICIONAL", 826);
define("WF_SUBACAO_AGUARDANDO_ANALISE_GESTOR", 455);
define("WF_SUBACAO_EMPENHO", 456);
define("WF_SUBACAO_PAGAMENTO", 457);
define("WF_SUBACAO_INDEFERIDA", 458);
define("WF_SUBACAO_APROVADA", 0);
define("WF_SUBACAO_ARQUIVADA", 0);
define("WF_SUBACAO_ANALISE_COMISSAO", 462);
define("WF_SUBACAO_RETORNADO_DE_DILIGENCIA", 1232);
define("WF_SUBACAO_BTN_ENVIAR_PARA_ANALISE", 1227);
define("WF_SUBACAO_BTN_ENVIAR_PARA_DILIGENCIA", 1229);
define("WF_SUBACAO_BTN_ENVIAR_PARA_EMPENHO", 1233);
define("WF_SUBACAO_ATUALIZACAO", 651);
define("WF_SUBACAO_ATUALIZACAO_ENVIAR_PARA_ANALISE", 1633);
define("WF_PAR_AEDID_ELABORACAO_ENVIAR_ANALISE", 1139);
/* * ** FIM WORKFLOW PAR 2010 *** */

# Escola Ativa
define('WF_TPDID_ESCOLA_ATIVA', 77);
define('PAR_ESCOLAATIVA_DATA_LIMITE_ADESAO', '20141230');

# Esta constante é o id do menu "Acompanhamento" que só deve estar disponível na própria página de acompanhamento do documento.
define("PAR_ESCONDE_ABA_ACOMPANHAMENTO", 13845);

# Tipos de Obra 
define("OBR_TPOID_MI_TIPO_B", 104);
define("OBR_TPOID_MI_TIPO_C", 105);
define("OBR_TPOID_REFORMA", 17);
define("OBR_TPOID_AMPLIACAO", 18);
define("OBR_TPOID_REFORMA_UAB", 29);
define("OBR_TPOID_AMPLIACAO_UAB", 30);
define("OBR_TPOID_TIPO_A_EMENDA", 48);
define("OBR_TPOID_AMPLIACAO_EMENDA", 64);
define("OBR_TPOID_REFORMA_EMENDA", 65);
define("OBR_TPOID_AMPLIACAO_UAB_EMENDA", 66);
define("OBR_TPOID_REFORMA_UAB_EMENDA", 67);
define("OBR_TPOID_ESCOLA_PROJETO_PROPRIO", 16);
define("OBR_TPOID_ESCOLA_PROJETO_PROPRIO_EMENDA", 56);
define("OBR_TPOID_COBERTURA_DE_QUADRA_ESCOLAR_PROJETO_PROPRIO_EMENDA", 57);
define("OBR_TPOID_QUADRA_ESCOLAR_COBERTA_PROJETO_PROPRIO_EMENDA", 63);

# Modelos de Documentos - par.modelosdocumentos
define("MDOID_TERMO_COMPROMISSO_MUNICIPIOS", 20);

if ($_SESSION['baselogin'] == 'simec_desenvolvimento') {
    # WORKFLOW - TIPO DE DOCUMENTO - Programa Mais Médicos
    define("WF_TPDID_MAIS_MEDICOS", 126);
    # WORKFLOW - TIPO DE DOCUMENTO - Programa Mais Médicos Novo Edital 2015
    define("WF_TPDID_MAIS_MEDICOS_NOVO_2015", 223);
    # QUESTIONARIO - Programa Mais Médicos
    define("QUEST_MAIS_MEDICOS", 89);
} else {
    # WORKFLOW - TIPO DE DOCUMENTO - Programa Mais Médicos
    define("WF_TPDID_MAIS_MEDICOS", 141);
    # WORKFLOW - TIPO DE DOCUMENTO - Programa Mais Médicos Novo Edital 2015
    define("WF_TPDID_MAIS_MEDICOS_NOVO_2015", 223);
    # QUESTIONARIO - Programa Mais Médicos
    define("QUEST_MAIS_MEDICOS", 89);
}

#ID DO PROGRAMA - PROGRAMA FINANCIAMENTO EJA.
define("PROG_PAR_PROGRAMA_FINANCIAMENTO_EJA", 188);

#ID DO PROGRAMA - EJA PRONATEC.
define("PROG_PAR_EJA_PRONATEC", 246);
#ID DO PROGRAMA - MAIS MÉDICO - NOVO EDITAL 2015.
define("PROG_PAR_MAIS_MEDICO_NOVO_2015", 251);

define("PROG_PAR_ADESAO_CONSELHO_ESCOLAR", 247);

#WORKFLOW - ESTADO DOCUMENTO - PROGRAMA FINANCIAMENTO EJA.
define("WF_EJA_EM_PREENCHIMENTO_UNIDADE", 565);
define("WF_EJA_EM_ANALISE_MEC", 566);
define("WF_EJA_CANCELADO", 567);
define("WF_EJA_APROVADO", 568);
define("WF_EJA_EM_DILIGENCIA", 572);

#WORKFLOW - ESTADO DOCUMENTO - PROGRAMA EJA PRONATEC.
define("WF_EJA_PRONATEC_EM_PREENCHIMENTO_UNIDADE", 1020);
define("WF_EJA_PRONATEC_EM_ANALISE_MEC", 1023);
define("WF_EJA_PRONATEC_CANCELADO", 1021);
define("WF_EJA_APRONATEC_PROVADO", 1024);
define("WF_EJA_PRONATEC_EM_DILIGENCIA", 1022);

#WORKFLOW - TIPO DE DOCUMENTO - PROGRAMA MAIS MÉDICO MEC - RECURSO QUESTIONÁRIO AVALIAÇÃO
define("WF_TPDID_MAIS_MEDICOS_RECURSO_QUESTIONARIO_AVALIACAO", 192);

#DATA DE FECHAMENTO DO RECURSO DO MUNICÍPIO MAIS MÉDICO.
define('DATA_FECHAMENTO_RECURSO', '2013-12-10GMT17:59:59');

#DATA DE FECHAMENTO DO RECURSO QUESTIONÁRIO AVALIAÇÃO MAIS MÉDICO.
define('DATA_FECHAMENTO_RECURSO_QUEST_AVAL', '2014-12-30GMT17:59:59');

# TIPO DE DOCUMENTO
define('TIPO_DE_DOCUMENTO_TERMO_ADITIVO', 21);
define('TIPO_DE_DOCUMENTO_TERMO_DE_COMPROMISSO', 102);
define('TIPO_DE_DOCUMENTO_TERMO_REFORMULADO', 103);

#WORKFLOW RESTRICOES PAR
define('TPDID_RESTRICAO_PAR', 193);
define('ESDID_EM_CADASTRAMENTO', 1216);
define('ESDID_EM_DILIGENCIA', 1217);
define('ESDID_EM_ANALISE_PROVIDENCIA', 1218);
define('ESDID_CONCLUIDO', 1219);
define('ESDID_EM_TRATATIVA_PROVIDENCIA', 1222);
define('ESDID_EM_ANALISE_DILIGENCIA', 1223);

#SASE
define('SASE_COM_LEI_SANCIONADA', 9);

#SCHEMAEDUCASENSO
define('SCHEMAEDUCACENSO', 'educacenso_2014');

?>
