<?PHP

    #CONSTANTES DE PERFIL
    define('PERFIL_RCS_SUPER_USUARIO', 1206);
    define('PERFIL_RCS_PROFESSOR', 1214);
    define('PERFIL_RCS_ADMINISTRADOR', 1215);
    
    define('PERFIL_RCS_INTERLOCUTOR', 1227);
    define('PERFIL_RCS_ADM_INSTITUCIONAL', 1225);
    
?>