CREATE DATABASE IF NOT EXISTS siminc2_desenvolvimento IF NOT EXISTS;
ALTER DATABASE siminc2_desenvolvimento SET datestyle TO European;
CREATE ROLE heronbonfim
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE ro_simec_c
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE ro_simec_t
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE "simec-web"
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE siminc
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE simec LOGIN
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT "simec-web" TO simec;
CREATE ROLE usr_simec LOGIN
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
ALTER USER usr_simec WITH ENCRYPTED PASSWORD '123456';