version: '2'
services:

  db:
    build: ./Docker/postgres/

    container_name: siminc2_db
    
    expose:
      - "5432"
    ports:
      - "5432:5432"
    
    env_file:
      - ./Docker/postgres/db-variables.env

    
  app:
    build: ./Docker/app/

    container_name: siminc2_app

    ports:
      - "8082:80"
      - "9002:9000"

    volumes: 
      - ./:/var/www/siminc2/

    env_file:
      - ./Docker/app/app-variables.env

    links:
      - "db"