<?php 
define('TIPO_AUTO_AVAL', 1);
define('TIPO_AVAL_SUPERIOR', 2);
define('TIPO_AVAL_CONSENSO', 3);
define('TIPO_MEDIA_CALCULADA', 0);
 
#Constantes para a tabela gestaopessoa.tiposituacaoservidor
define('SITUACAO_ATIVO_PERMANENTE', 1);
define('REQUISITADO', 3);
define('NOMEADO_CARGO_COMIS', 4);
define('SITUACAO_CEDIDO', 8);
define('SITUACAO_EXCEDENTE', 11);
define('REQ_DE_OUTROS_ORGAOS', 14);
define('EXERC_DESCENT_CARREI', 18);
define('SITUACAO_ATIVO_PERM_L', 21);
define('SITUACAO_ANISTIADO', 22);
define('SITUACAO_EXERC', 44);
define('CLT_ANS_DEC_6657_08', 43);

define('PERFIL_SUPER_USER', 302);
define('PERFIL_AVAL_SERV_AVALIACAO', 304);
define('PERFIL_AVAL_SERV_SERVIDOR', 400);#USADO NO MODULO AVALIAวรO.
define('PERFIL_AVAL_SERV_ADMINISTRADOR', 305);
define('PERFIL_AVAL_SERV_CONSULTA', 306); 
define('PERFIL_AVAL_EQUIPE_APOIO', 1045);

#Definindo constantes do controle de vํnculos , serใo usados pela fun็ใo controlaDadoFuncional();
define( 'VINCULO_EFETIVO', 1); 
define( 'VINCULO_CEDIDO', 2);  
define( 'VINCULO_CTU', 3);  
define( 'VINCULO_CONSULTOR', 4);  
define( 'VINCULO_EXERCICIODES', 5);  
define( 'VINCULO_EXERCICIOPRO', 6);  
define( 'VINCULO_TERCEIRIZADO', 7);  
define( 'VINCULO_ANISTIADO_CLT', 8);  
define( 'VINCULO_CARGOCOMISSIONADO', 9);  
define( 'VINCULO_REQUISITADO', 10);  
define( 'VINCULO_COLABORACAO_TECNICA', 11); 
define( 'VINCULO_EXAMINADOR_EXTERNO', 12); 
 
define( 'PERFIL_FT_CONSULTA_GERAL',334);
define( 'PERFIL_FT_ADMINISTRADOR_GERAL',335);
define( 'PERFIL_FT_ADMINISTRADOR_CONTRATO',336);
define( 'PERFIL_FT_ADMINISTRADOR_PESSOAL',337);
define( 'PERFIL_FT_ADMINISTRADOR_PROJETO',338);
define( 'PERFIL_FT_FISCAL_CONTRATO',339);
define( 'PERFIL_FT_FISCAL_PESSOAL',340);
define( 'PERFIL_FT_FISCAL_PROJETO',341);


define( 'PERFIL_SERVIDOR',400);#USADO NO MODULO FORวA DE TRABALHO.
define( 'PERFIL_CONSULTOR',401);
define( 'PERFIL_TERCEIRIZADO',402);

define( 'PERFIL_GESTOR',868);
define( 'PERFIL_AIDP',869);


#-------------------------------------------- CONSTANTES SISTEMAS GESTรO PESSOEAS - MODULO AVALIAวรO DE SERVIDOR ---------------------------------#

//define('DATA_DE_FECHAMENTO_AVALIACAO', '2013-12-31T23:59:59-02:00' ); (nใo ้ usado mais).

if($_SESSION['baselogin'] == 'simec_desenvolvimento'){
    
    #VARIAVEIS DE MENUS/ABAS.
    define('ABA_CAD_AVALIACAO_SERVIDOR_ADM', 57668);#ABA CADASTRO DE AVALIAวรO DO SERVIDOR CORRESPONDENTE A PERFIL ADMINISTRADOR E SUPER USUARIO
    define('ABA_CAD_AVALIACAO_SERVIDOR', 57665);#ABA CADASTRO DE AVALIAวรO DO SERVIDOR.
    define('ABA_LISTA_SERVIDORES_EQUIPES', 57666);#ABA LISTAM DE SERVIDORES E DE FECHES E SUAS RESPECTIVAS ESQUIPES.
    define('ABA_FORCA_TRAB_MENU_INICIAL', 58321);#ABA DO MODULO FORวA DE TRABALHO COM A LISTAGEM DE PESSOAL EFETIVO, PESSOAL CEDIDO E PAINEL.
    
    #COSNTANTES PERFIL MODULO AVALIAวรO.
    define('PERFIL_AVAL_EQUIPE_APOIO', 948);
        
}else{
    
    #VARIAVEIS DE MENUS/ABAS.
    define('ABA_CAD_AVALIACAO_SERVIDOR_ADM', 57740);#ABA CADASTRO DE AVALIAวรO DO SERVIDOR CORRESPONDENTE A PERFIL ADMINISTRADOR E SUPER USUARIO
    define('ABA_CAD_AVALIACAO_SERVIDOR', 57741);#ABA CADASTRO DE AVALIAวรO DO SERVIDOR.
    define('ABA_LISTA_SERVIDORES_EQUIPES', 57742);#ABA LISTAM DE SERVIDORES E DE FECHES E SUAS RESPECTIVAS ESQUIPES
    define('ABA_FORCA_TRAB_MENU_INICIAL', 57890);#ABA DO MODULO FORวA DE TRABALHO COM A LISTAGEM DE PESSOAL EFETIVO, PESSOAL CEDIDO E PAINEL.
    
    #COSNTANTES PERFIL MODULO AVALIAวรO.
    define('PERFIL_AVAL_EQUIPE_APOIO', 1045);    
    
}

#DATA REFERENTE AO PERอODO DE AVALIAวรO. USADA PARA VISUALIZAวรO NO CABEวALHO EM TELA.
define('DATA_PERIODO_INICO_AVALIACAO', '22/09/2015');
define('DATA_PERIODO_FINAL_AVALIACAO', '31/10/2015');

#DATA FINAL PARA A REALIZAวรO DA AVALIAวรO. USADA NA FUNวรO 'prazoVencido()'.
define('DATA_AVALIAวรO_FINALIZADA', '31/12/2015'); 

#DATA DO CICLO AVALIATIVO GESTรO PESSOAS.
define('DATA_CICLO_AVALIATIVO_INICIAL', '01/11/2014'); 
define('DATA_CICLO_AVALIATIVO_FINAL', '31/10/2015'); 


#ID DA PERGUNTA DO QUESTIONARIO DE AVALIAวรO. USADA PARA VIRIFICAR O NUMERO DE PESSOAS QUE FIZERAM A AVALIAวรO DE EQUIPE. ษ DEFINIDO APENAS UMA 
#PERGUNTA PARA TER O NUMERO EXATO DE PESSOAS QUE RESPONDERAM O QUESTIONARIO E ษ USADO UMA CONSTANTE PQ CADA ANO DE MUDA O ID DAS PERGUNTAS.
switch ( $_SESSION['exercicio'] ) {
    case 2009:
        define('ID_PERG_RESPAVALIACAO_QTR_RESP', 9);
        break;
    case 2010:
        define('ID_PERG_RESPAVALIACAO_QTR_RESP', 16);
        break;
    case 2011:
        define('ID_PERG_RESPAVALIACAO_QTR_RESP', 23);
        break;
    case 2012:
        define('ID_PERG_RESPAVALIACAO_QTR_RESP', 30);
        break;
    case 2013:
        define('ID_PERG_RESPAVALIACAO_QTR_RESP', 37);
        break;
    case 2014:
        define('ID_PERG_RESPAVALIACAO_QTR_RESP', 44);
        break;
    case 2015:
        define('ID_PERG_RESPAVALIACAO_QTR_RESP', 51);
        break;
}

#------------------------------------------- CONSTANTES SISTEMAS GESTรO PESSOEAS - MODULO CESSรO/PRORROGAวรO SERVIDOR -------------------------------#

if($_SESSION['baselogin'] == 'simec_desenvolvimento'){
    
    #CONSTANTES PERFIL MODULO CESSรO/PRORROGAวรO SERVIDORES.
    define( 'PERFIL_CESSAO_MOVIMENTACAO', 926);
    define( 'PERFIL_CESSAO_CAP', 924);
    define( 'PERFIL_CESSAO_CGGP', 925);

    define( 'PERFIL_CESSAO_SAA_ADM', 920);
    define( 'PERFIL_CESSAO_GABINTE_MIN_ADM', 923);
    define( 'PERFIL_CESSAO_CGGA_ADM', 922);
    define( 'PERFIL_CESSAO_CGGP_ADM', 921);

    define( 'PERFIL_CESSAO_CONJUR_ADM', 914);
    define( 'PERFIL_CESSAO_CONJUR_ADVOGADO', 927);
    define( 'PERFIL_CESSAO_CONJUR_COORDENACAO', 928);
    
    #CONSTANTES DO WORKFLOW - REFERENTES AO TPDID.
    define( 'WF_CESSAO_FLUXO_1', 110);#TIPO DE DOCUEMNTO CESSรO FLUXO - 1 - CESSรO/PRORROGAวรO.
    define( 'WF_CESSAO_FLUXO_2', 111);#TIPO DE DOCUEMNTO CESSรO FLUXO - 2 - CESSรO/PRORROGAวรO.
    define( 'WF_CESSAO_FLUXO_3', 112);#TIPO DE DOCUEMNTO CESSรO FLUXO - 3 - CESSรO/PRORROGAวรO.
    define( 'WF_CESSAO_FLUXO_4', 113);#TIPO DE DOCUEMNTO CESSรO FLUXO - 4 - CESSรO/PRORROGAวรO.
    
    #VARIAVEIS DE MENUS/ABAS.
    define('PAGINA_INICIAL_ABA_LISTAGEM', 57645);#ABA LISTAGEM PAGINA INICIAL.
    define('ABA_CAD_CESSAO_SERVIDOR', 57637);#ABA CADASTRO DE CESSรO SERVIDOR.
    define('ABA_CAD_CONSULTA_SERVIDOR', 57647);#ABA CADASTRO DE CONSULTA SERVIDOR.
    define('ABA_CAD_PRORROGACAO_SERVIDOR', 57646);#ABA CADASTRO DE PRORROGAวรO SERVIDOR.
    define('ABA_CAD_REITERACAO_SERVIDOR', 57648);#ABA CADASTRO DE REITERAวรO SERVIDOR.
    
}else{
    
    #CONSTANTES PERFIL MODULO CESSรO/PRORROGAวรO SERVIDORES.
    define( 'PERFIL_CESSAO_MOVIMENTACAO', 1005);
    define( 'PERFIL_CESSAO_CAP', 997);
    define( 'PERFIL_CESSAO_CGGP', 999);

    define( 'PERFIL_CESSAO_SAA_ADM', 1006);
    define( 'PERFIL_CESSAO_GABINTE_MIN_ADM', 1004);
    define( 'PERFIL_CESSAO_CGGA_ADM', 998);
    define( 'PERFIL_CESSAO_CGGP_ADM', 1000);

    define( 'PERFIL_CESSAO_CONJUR_ADM', 1001);
    define( 'PERFIL_CESSAO_CONJUR_ADVOGADO', 1002);
    define( 'PERFIL_CESSAO_CONJUR_COORDENACAO', 1003);
    
    #CONSTANTES DO WORKFLOW - REFERENTES AO TPDID.
    define( 'WF_CESSAO_FLUXO_1', 130);#TIPO DE DOCUEMNTO CESSรO FLUXO - 1 - CESSรO/PRORROGAวรO.
    define( 'WF_CESSAO_FLUXO_2', 131);#TIPO DE DOCUEMNTO CESSรO FLUXO - 2 - CESSรO/PRORROGAวรO.
    define( 'WF_CESSAO_FLUXO_3', 132);#TIPO DE DOCUEMNTO CESSรO FLUXO - 3 - CESSรO/PRORROGAวรO.
    define( 'WF_CESSAO_FLUXO_4', 133);#TIPO DE DOCUEMNTO CESSรO FLUXO - 4 - CESSรO/PRORROGAวรO.

    #VARIAVEIS DE MENUS/ABAS.
    define('PAGINA_INICIAL_ABA_LISTAGEM', 57727);#ABA LISTAGEM PAGINA INICIAL.
    define('ABA_CAD_CESSAO_SERVIDOR', 57723);#ABA CADASTRO DE CESSรO SERVIDOR.
    define('ABA_CAD_CONSULTA_SERVIDOR', 57724);#ABA CADASTRO DE CONSULTA SERVIDOR.
    define('ABA_CAD_PRORROGACAO_SERVIDOR', 57725);#ABA CADASTRO DE PRORROGAวรO SERVIDOR.
    define('ABA_CAD_REITERACAO_SERVIDOR', 57726);#ABA CADASTRO DE REITERAวรO SERVIDOR.      
    
}

#CONSTANTES WORKFLOW - CESSAO-FLUXO-1
define( 'EM_PROCESSAMENTO_CGGP', 690);
define( 'EM_VALIDACAO_UNIDADE_ORGAO_LOTACAO',  691);
define( 'EM_ANALISE_CGGP', 692);
define( 'EM_ANALISE_CONJUR', 693);
define( 'EM_ANALISEA_GABINETE_MINISTRO', 694);
define( 'EM_ANALISE_CGGA', 695);
define( 'PREENCHIMENTO_PORTARIA_CGGP', 696);
define( 'PROCESSO_FINALIZADO', 697);
define( 'EM_ANALISE_SAA', 698);

?>