<?php
//CONSTANTE DA SITUA��O DA FASE
define( 'SITUACAO_FASE_CONCLUIDA', 3 );
define( 'SITUACAO_FASE_CANCELADA', 5 );

// INDICA O PROJETO PDE
define( 'PROJETO_PDE', 3 );

// INDICA OS PERFIS EM RELAÇÃO AO MÓDULO
switch( $_SESSION['sisid'] ) {
	case 10: # PDE
		define( 'PERFIL_GESTOR',  82 );
		define( 'PERFIL_GERENTE', 90 );
		define( 'PERFIL_EQUIPE_APOIO_GESTOR',  85 );
		define( 'PERFIL_EQUIPE_APOIO_GERENTE', 91 );
		define( 'PERFIL_ASSESSOR', 159 );
		// força a seleção do projeto pde
		$_SESSION['projeto'] = PROJETO_PDE;
		break;
	case 17: # PROJETOS

		// usado na tela de listagem de projetos
		define( 'PERFIL_ADMINISTRADOR', 103 );
		define( 'PERFIL_CONSULTA', 104 );

		define( 'PERFIL_GESTOR',  98 );
		define( 'PERFIL_GERENTE', 101 );
		define( 'PERFIL_EQUIPE_APOIO_GESTOR',  99 );
		define( 'PERFIL_EQUIPE_APOIO_GERENTE', 102 );
		if ( $_SESSION['projeto'] == PROJETO_PDE ) {
			$_SESSION['projeto'] = null;
		}
		break;
}

// INDICA O PROJETO A SER TRABALHADO
define( 'PROJETO', $_SESSION['projeto'] ? (int)$_SESSION['projeto'] : null );

define( 'PERFIL_SUPERUSER', 258 );
define( 'PERFIL_GESTOR', 259 );
define( 'PERFIL_EQUIPE_APOIO_GESTOR', 260 );
define( 'PROJETO_PDE', 3 );


define( 'PERFIL_COORDENADOR_ACAO_SIGPLAN', 264 );


define( 'PERFIL_APOIO_COORDENADOR_PLANEJAMENTO', 262 );
define( 'PERFIL_COORDENADOR_PLANEJAMENTO', 266 );

define( 'PERFIL_APOIO_COORDENADOR_ORCAMENTO', 261 );
define( 'PERFIL_COORDENADOR_ORCAMENTO', 265 );

define( 'PERFIL_TECNICO_DEPARTAMENTO', 269 );
define( 'PERFIL_TECNICO_UNIDADE_DESCENTRALIZADA', 270 );
define( 'PERFIL_GESTOR_UNIDADE_DESCENTRALIZADA', 268 );
define( 'PERFIL_APOIO_DIRETOR_DEPARTAMENTO', 263 );
define( 'PERFIL_DIRETOR_DEPARTAMENTO', 267 );

define( 'PERFIL_COORDENADOR_GERAL_PLANEJAMENTO_ORCAMENTO', 271 );

define( 'WF_TIPODOC_PLANOACAO', 5 );


define ( 'ACAO_ESTADO_DOC_ENVIADO', 55 );
define ( 'ACAO_ESTADO_DOC_CANCELADO', 60 );

define ( 'PLANO_INTERNO_APROVADO', 56 );
define ( 'PLANO_INTERNO_REPROVADO', 61 );

define ( 'UNIDADE_IPHAN', 42204 );

// DEFINE URL PARA ACESSO AO MINC
define( 'URL_MINC', 'http://minc/' );
//define( 'URL_MINC', 'http://simc.cultura.gov.br/');
//define( 'URL_MINC', 'http://simchomolog.cultura.gov.br/');

define( 'SISID_PDE', 11 );

// INDICA OS ESTADOS DAS ATIVIDADES
define( 'STATUS_NAO_INICIADO', 1 );
define( 'STATUS_EM_ANDAMENTO', 2 );
define( 'STATUS_SUSPENSO',     3 );
define( 'STATUS_CANCELADO',    4 );
define( 'STATUS_CONCLUIDO',    5 );

// INDICA A SITUAÇÃO DA ABA DE CONTRATAÇÃO
define( 'CONCLUIDA',    4 );
define( 'NAO_SE_APLICA',    5 );

define( 'WORKFLOW_EM_ELABORACAO', 28 );

//UNIDADE_DESCENTRALIZADA
define( 'WORKFLOW_ANALISE_UNIDADE_DESCENTRALIZADA', 29 );
define( 'WORKFLOW_ACAO_ANALISE_UNIDADE_DESCENTRALIZADA', 51 );

//PRESIDENCIA
define( 'WORKFLOW_ANALISE_PRESIDENCIA', 42 );
define( 'WORKFLOW_ACAO_ANALISE_PRESIDENCIA', 81 );

//COORDENACAO_PLANEJAMENTO
define( 'WORKFLOW_ANALISE_COORDENACAO_PLANEJAMENTO', 33 );
define( 'WORKFLOW_ACAO_ANALISE_COORDENACAO_PLANEJAMENTO', 80 );

//ACAO_PLANO_PLURIANUAL
define( 'WORKFLOW_ANALISE_ACAO_PLANO_PLURIANUAL', 31 );
define( 'WORKFLOW_ACAO_ANALISE_ACAO_PLANO_PLURIANUAL', 52 );

define( 'WORKFLOW_ANALISE_DEPARTAMENTO', 32 );
define( 'WORKFLOW_AGUARDANDO_PI', 34 );
define( 'EM_ANALISE_COORDENACAO_ORCAMENTO_FINANCAS', 37 );
define( 'WORKFLOW_AGUARDANDO_DESCENTRALIZACAO', 38 );

define( 'IGNORAR_ESTADOS_ALERTA_TRAMITACAO', '28, 38, 40, 41');

define( 'LIMITE_HORAS_ALERTA_TRAMITACAO', 120 );

// ESFERA DA A��O
define( 'ESFERA_FEDERAL', 1 );
define( 'ESFERA_ESTADUAL_DISTRITO_FEDERAL', 2 );
define( 'ESFERA_MUNICIPAL', 3 );
define( 'ESFERA_EXTERIOR', 4 );

//CONSTANTES DO WORKFLOW DE PLANEJAMENTO
define ('WF_PLANEJAMENTO',100);

define ('WF__PLANEJAMENTO_ESTADO_CADASTRAMENTO',500);
define ('WF__PLANEJAMENTO_ESTADO_AGUARDANDOAPROVACAO',501);
define ('WF__PLANEJAMENTO_ESTADO_APROVADO',502);
define ('WF__PLANEJAMENTO_ESTADO_REPROVADO',503);
define ('WF__PLANEJAMENTO_ESTADO_AGUARDANDOCORRECAO',504);

define ('WF__PLANEJAMENTO_ACAO_ENVIARAPROVACAO',1000);

//CONSTANTES DO WORKFLOW DE DETALHE DO PLANEJAMENTO
define ('WF_DETALHE_PLANEJAMENTO',101);

define ('WF_DETALHE_PLANEJAMENTO_ESTADO_AGUARDANDOCORRECAO',515);
define ('WF_DETALHE_PLANEJAMENTO_ESTADO_AGUARDANDOAPROVACAOPI',508);
define ('WF_DETALHE_PLANEJAMENTO_ESTADO_AGUARDANDODESCENTRALIZACAO',512);
?>
