<?php

define("SASE_SISID", 183); // nao assessorado


if( $_SESSION['baselogin'] == 'simec_desenvolvimento' ){

	define("ESDID_SASE_NAO_ASSESSORADO", 963); // nao assessorado
	define("ESDID_SASE_ASSESSORADO", 964); // assessorado
	define("ESDID_SASE_COM_COMISSAO", 965); // com comissao
	define("ESDID_SASE_TEM_DIAGNOSTICO", 966); // tem diagnostico
	define("ESDID_SASE_TEM_TEXTO_BASE", 967); // tem texto-base
	define("ESDID_SASE_REALIZOU_CONFERENCIA", 968); // realizou a conferencia
	define("ESDID_SASE_TEM_PROJETO_LEI", 969);// tem projeto de lei - pl

	define("TPDID_SASE_ASSESSORAMENTO", 151);
	define("TPDID_SASE_QUESTOESPONTUAIS", 152);

}else{

	define("SASE_SISID", 183);

	// ESTADOS DO DOCUMENTO (WORKFLOW)
	define("ESDID_SASE_SEM_INFORMACAO", 1117); // nao assessorado
	define("ESDID_SASE_SEM_COMISSAO_COORDENADORA_CONSTITUIDA", 1118); // assessorado
	define("ESDID_SASE_COM_COMISSAO_COORDENADORA_CONSTITUIDA", 1119); // com comissao
	define("ESDID_SASE_COM_DIAGNOSTICO_CONCLUIDO", 1120); // tem diagnostico
	define("ESDID_SASE_COM_DOCUMENTO_BASE_ELABORADO", 1121); // tem texto-base
	define("ESDID_SASE_COM_CONSULTA_PUBLICA_REALIZADA", 1122); // realizou a conferencia
	define("ESDID_SASE_COM_PROJETO_DE_LEI_ELABORADO", 1126);// tem projeto de lei - pl
	define("ESDID_SASE_COM_PROJETO_DE_LEI_ENVIADO_PELO_LEGISLATIVO", 1127); // Apreciação Executivo
	define("ESDID_SASE_COM_LEI_APROVADA", 1123); // Apreciação Legislativo
	define("ESDID_SASE_COM_LEI_SANCIONADA", 1124); // Publicação do Plano
    define("ESDID_SASE_FINALIZADO", 1125); // Finalizado

    // ESTADOS DO DOCUMENTO (AVALIADOR EDUCACIONAL)
    define("ESDID_SASE_EM_CADASTRAMENTO_PELO_TECNICO", 1412);
    define("ESDID_SASE_EM_CORRECOES_PELO_TECNICO", 1417);
    define("ESDID_SASE_EM_ANALISE_SUPERVISOR", 1416);
    define("ESDID_SASE_EM_RE_ANALISE_SUPERVISOR", 1418);
    define("ESDID_SASE_EM_CADASTRAMENTO_PELO_SUPERVISOR", 1413);
    define("ESDID_SASE_EM_CORRECOES_PELO_SUPERVISOR", 1419);
    define("ESDID_SASE_EM_ANALISE_PELO_COORDENADOR_ESTADUAL", 1420);
    define("ESDID_SASE_EM_RE_ANALISE_PELO_COORDENADOR_ESTADUAL", 1421);
    define("ESDID_SASE_EM_CADASTRAMENTO_PELO_SUPERVISOR_GERAL", 1414);
    define("ESDID_SASE_EM_CORRECOES_PELO_SUPERVISOR_GERAL", 1422);
    define("ESDID_SASE_EM_CADASTRAMENTO_PELO_COORDENADOR_ESTADUAL", 1415);
    define("ESDID_SASE_EM_CORRECOES_PELO_COORDENADOR_ESTADUAL", 1423);
    define("ESDID_SASE_EM_ANALISE_PELO_MEC", 1424);
    define("ESDID_SASE_EM_RE_ANALISE_PELO_MEC", 1425);
    define("ESDID_SASE_RELATORIO_FINALIZADO", 1426);

	// TIPO DE DOCUMENTO (WORKFLOW) .
	define("TPDID_SASE_ASSESSORAMENTO", 182);
	define("TPDID_SASE_QUESTOESPONTUAIS", 181);
    define("TPDID_SASE_AVALIADOREDUCACIONAL", 217);
    define("TPDID_SASE_PLANODECARREIRA", 238);
    define("TPDID_SASE_SITUACAO_PLANOCARREIRA", 240);

	// PERFIS (SEGURANCA).
	define("PFLCOD_SASE_EXECUTIVO", 1249); // COORDENADOR
	define("PFLCOD_SASE_SUPERVISOR", 1250);
	define("PFLCOD_SASE_TECNICO", 1251);
	define("PFLCOD_SASE_SUPER_USUARIO", 1201);
	define("PFLCOD_SASE_CADASTRADOR", 1203);
	define("PFLCOD_SASE_CONSULTA", 1210);
	define("PFLCOD_SASE_ADMINISTRADOR", 1202);
	define("PFLCOD_SASE_SUPERVISOR_GERAL", 1318);
    define("PFLCOD_SASE_CONSULTA_LEI_PEE_PME", 1408);
    define("PFLCOD_SASE_COORDENADOR_ESTADUAL_DIVAPE", 1426);
    define("PFLCOD_SASE_TECNICO_DIVAPE",1427);
}