<?php 

// Workflow
define('WF_TPDID_SIC', 							69);

define('WF_ESDID_EM_CADASTRAMENTO', 			486);
define('WF_ESDID_ANALISE_AREA_RESPONSAVEL', 	487);
define('WF_ESDID_FINALIZADO', 					488);
define('WF_ESDID_DEVOLVIDO_PELA_AREA_RESP', 	476);
define('WF_ESDID_ANALISE_NAI', 					477);
define('WF_ESDID_CANCELADO', 					475);
define('WF_ESDID_RECURSO_1_INSTANCIA', 			481);
define('WF_ESDID_RECURSO_2_INSTANCIA', 			482);
define('WF_ESDID_ANALISE_1_RECURSO', 			478);
define('WF_ESDID_ANALISE_2_RECURSO', 			479);
define('WF_ESDID_FINALIZADO_1_INSTANCIA', 		480);
define('WF_ESDID_FINALIZADO_2_INSTANCIA', 		516);

// Perfis
define('SIC_PERFIL_AREA_RESPONSAVEL', 			760);
define('SIC_PERFIL_CADASTRADOR', 				759);
define('SIC_PERFIL_ADMINISTRADOR', 				699);
define('SIC_PERFIL_SUPER_USUARIO', 				758);
define('SIC_PERFIL_GESTOR_SOLICITACOES',	   1025);
define('SIC_PERFIL_ORGAO_CONTROLE',     	   1394);

// Dados
define('EMAIL_PRINCIPAL_SIC', $_SESSION['email_sistema']);

?>