<section id="login" class="login">
	<div class="content">
		<?php if ( $_SESSION['MSG_AVISO'] ): ?>
			<div class="col-md-4 col-md-offset-4">
				<div class="alert alert-danger" style="font-size: 14px; line-height: 20px;">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<i class="fa fa-bell"></i> <?php echo implode( "<br />", (array) $_SESSION['MSG_AVISO'] ); ?>
				</div>
			</div>
		<?php endif; ?>
		<?php $_SESSION['MSG_AVISO'] = array(); ?>
	
		<div class="col-md-4 col-md-offset-4">
			<div class="panel panel-default">
				<div class="panel-heading">
					<span class="glyphicon glyphicon-lock"></span> Login
				</div>
				<div class="panel-body">
					<form class="form-horizontal" role="form" method="post" action="<?php echo $this->url(array('module' => 'default', 'controller' => 'usuario', 'action' => 'login')); ?>">
						<input type="hidden" name="versao" value="<?php echo $_POST['versao']; ?>"/>
						<input type="hidden" name="formulario" value="1"/>

						<?php if (APPLICATION_ENV != 'production') : ?>
						<input type="hidden" name="baselogin" id="baselogin" value="simec_espelho_producao"/>
						<div class="form-group text-right">
							<div class="col-lg-12">
								<div class="make-switch" style="width: 140px;" data-on-label="Espelho" data-off-label="Desenv. " data-on="primary" data-off="danger">
									<input type="checkbox" name="baselogincheck" id="baselogincheck" value="simec_espelho_producao" checked="checked" />
								</div>
							</div>
						</div>
						<?php endif; ?>
						
						<div class="form-group">
							<div class="col-sm-12">
								<input type="text" class="form-control cpf" name="usucpf" id="usucpf" placeHolder="CPF" required="">
							</div>
						</div>
						<div class="form-group">
							<div class="col-sm-12">
								<input type="password" class="form-control" name="ususenha" id="ususenha" placeHolder="Senha" required="">
							</div>
						</div>
						<div class="form-group" style="font-size: 14px;">
							<div class="col-sm-8">
								<i class="fa fa-key"></i> <a href="recupera_senha.php" style="color: #c8c5c5">Esqueci minha senha?</a>
							</div>
							<div class="col-sm-4 text-right">
								<button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Acessar</button>
							</div>
						</div>
					</form>
				</div>
				<div class="panel-footer text-center" style="font-size: 14px;">
				   <div class="btn-group">
						Não tem acesso ainda?&nbsp;
						<i class="fa fa-user"></i> 
						<a href="cadastrar_usuario.php" id="btn-cadastro" style="color: #c8c5c5">Solicitar acesso</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>