<?php

$textoEmail = "

<style>
    body {
        padding-top: 0 !important;
        padding-bottom: 0 !important;
        padding-top: 0 !important;
        padding-bottom: 0 !important;
        margin: 0 !important;
        width: 100% !important;
        -webkit-text-size-adjust: 100% !important;
        -ms-text-size-adjust: 100% !important;
        -webkit-font-smoothing: antialiased !important;
    }

    p,
    h1,
    h2,
    ul,
    ol,
    li,
    div {
        margin: 0;
        padding: 0;
        color: #273a4a !important;
    }

    h1,
    h2 {
        font-weight: normal;
        background: transparent !important;
        border: none !important;
    }

    @media only screen and (max-width:480px) {
        table[class='MainContainer'],
        td[class='cell'] {
            width: 100% !important;
            height: auto !important;
        }
        td[class='specbundle'] {
            width: 100% !important;
            float: left !important;
            font-size: 13px !important;
            line-height: 17px !important;
            display: block !important;
            padding-bottom: 15px !important;
        }
        td[class='specbundle2'] {
            width: 80% !important;
            float: left !important;
            font-size: 13px !important;
            line-height: 17px !important;
            display: block !important;
            padding-bottom: 10px !important;
            padding-left: 10% !important;
            padding-right: 10% !important;
        }
        td[class='spechide'] {
            display: none !important;
        }
        img[class='banner'] {
            width: 100% !important;
            height: auto !important;
        }
        td[class='left_pad'] {
            padding-left: 15px !important;
            padding-right: 15px !important;
        }
    }

    @media only screen and (max-width:540px) {
        table[class='MainContainer'],
        td[class='cell'] {
            width: 100% !important;
            height: auto !important;
        }
        td[class='specbundle'] {
            width: 100% !important;
            float: left !important;
            font-size: 13px !important;
            line-height: 17px !important;
            display: block !important;
            padding-bottom: 15px !important;
        }
        td[class='specbundle2'] {
            width: 80% !important;
            float: left !important;
            font-size: 13px !important;
            line-height: 17px !important;
            display: block !important;
            padding-bottom: 10px !important;
            padding-left: 10% !important;
            padding-right: 10% !important;
        }
        td[class='spechide'] {
            display: none !important;
        }
        img[class='banner'] {
            width: 100% !important;
            height: auto !important;
        }
        td[class='left_pad'] {
            padding-left: 15px !important;
            padding-right: 15px !important;
        }
    }

    .contentEditable h2.big,
    .contentEditable h1.big {
        font-size: 26px !important;
    }

    .contentEditable h2.bigger,
    .contentEditable h1.bigger {
        font-size: 37px !important;
    }

    td,
    table {
        vertical-align: top;
    }

    td.middle {
        vertical-align: middle;
    }

    a.link1 {
        font-size: 13px;
        color: #27A1E5;
        line-height: 24px;
        text-decoration: none;
    }

    a {
        text-decoration: none;
    }

    h2,
    h1 {
        line-height: 20px;
    }

    p {
        font-size: 14px;
        line-height: 21px;
        color: #AAAAAA;
    }

    span {
        font-weight: bold;
        padding-left: 7px;
    }

    a {
        color: #273a4a;
    }

    .bgItem {
        background: #ffffff;
    }

    .bgBody {
        background: #ffffff;
    }

    img {
        outline: none;
        text-decoration: none;
        -ms-interpolation-mode: bicubic;
        width: auto;
        max-width: 100%;
        clear: both;
        display: block;
        float: none;
    }

    .left {
        padding-left: 2%;
        padding-right: 2%;
        margin-bottom: 2%;
        padding-bottom: 2%;
    }

    .valor {
        font-weight: normal;
    }

</style>

<body style='background-color: #f3f3f4;padding-top: 0;padding-bottom: 0;padding-top: 0;padding-bottom: 0;background-repeat: repeat;width: 100% !important;-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;-webkit-font-smoothing: antialiased;'>
    <table width='100%' border='0' cellspacing='0' cellpadding='0'>
        <tbody>
            <tr>
                <td>
                    <table width='850' border='0' cellspacing='0' cellpadding='0' align='center' bgcolor='#ffffff' style='width: 850px;font-family:helvetica, sans-serif;' class='MainContainer'>

                        <tbody>
                            <tr>
                                <td>
                                    <table width='100%' border='0' cellspacing='0' cellpadding='0'>
                                        <tbody>
                                            <tr>
                                                <td valign='top' width='20'>&nbsp;</td>
                                                <td>
                                                    <table width='100%' border='0' cellspacing='0' cellpadding='0'>
                                                        <tbody>
                                                            <tr>
                                                                <td class='movableContentContainer'>
                                                                    <div class='movableContent' style='border: 0px;padding-top: 0px;position: relative;background-color: #273a4a;'>
                                                                        <table width='100%' border='0' cellspacing='0' cellpadding='0'>
                                                                            <tbody>
                                                                                <tr>
                                                                                    <td height='15'></td>
                                                                                </tr>
                                                                                <tr>
                                                                                    <td>
                                                                                        <table width='100%' border='0' cellspacing='0' cellpadding='0'>
                                                                                            <tbody>
                                                                                                <tr>
                                                                                                    <td valign='top'>
                                                                                                        <table width='100%' border='0' cellspacing='0' cellpadding='0'>
                                                                                                            <tbody>
                                                                                                                <tr>

                                                                                                                    <td width='10' valign='top'>&nbsp;</td>
                                                                                                                    <td valign='middle' style='vertical-align: middle;'>
                                                                                                                        <div class='contentEditableContainer contentTextEditable'>
                                                                                                                            <div class='contentEditable' style='text-align: left;font-weight: light; color:#555555;font-size:26;line-height: 39px;font-family: Helvetica Neue;'>
                                                                                                                                <img src='http://siminc2.cultura.gov.br/zimec/public/img/logo-simec.png'>
                                                                                                                            </div>
                                                                                                                        </div>
                                                                                                                    </td>
                                                                                                                </tr>
                                                                                                            </tbody>
                                                                                                        </table>
                                                                                                    </td>
                                                                                                    <td valign='top' width='90' class='spechide'>&nbsp;</td>
                                                                                                    <td valign='middle' style='vertical-align: middle;' width='150'>
                                                                                                        <div class='contentEditableContainer contentTextEditable'>

                                                                                                        </div>
                                                                                                    </td>
                                                                                                </tr>
                                                                                            </tbody>
                                                                                        </table>
                                                                                    </td>
                                                                                </tr>
                                                                                <tr>
                                                                                    <td height='15'></td>
                                                                                </tr>
                                                                                <tr>

                                                                                </tr>
                                                                            </tbody>
                                                                        </table>
                                                                    </div>



                                                                    <div class='movableContent' style='padding-top: 0px;position: relative; background-color:#eaeaea;'>
                                                                        <table width='100%' border='0' cellspacing='0' cellpadding='0' style='padding-left: 16px;'>
                                                                            <tbody>
                                                                                <tr>
                                                                                    <td height='30'></td>
                                                                                </tr>
                                                                                <tr>
                                                                                    <td>
                                                                                        <table width='100%' border='0' cellspacing='0' cellpadding='0'>
                                                                                            <tbody>
                                                                                                <tr>
                                                                                                    <td class='specbundle'>
                                                                                                        <div class='contentEditableContainer contentTextEditable'>
                                                                                                            <div class='contentEditable' style='text-align: left; line-height: 22px;'>
                                                                                                                <div style='background-color: white;padding-top: 0px;position: relative;width: 108%; border-top: 3px solid #54b3a3;'>
                                                                                                                    <br>

                                                                                                                    <div class='left'>
                                                                                                                        <p><b>ID: </b>". $pi['pliid']. "</p>

                                                                                                                        ". ($pi['plicod']? "<p><b>C&oacute;digo PI: </b>". $pi['plicod']. "</p>": NULL ). "
                                                                                                                        <p><b>T&iacute;tulo: </b>". $pi['plititulo']. "</p>
                                                                                                                        <br>


                                                                                                                        <p><b>PTRES: </b><a href='#'>". $ptres['ptres']. "</a></p>
                                                                                                                        <p><b>Unidade: </b>". $ptres['unicod']. " &ndash; ". $ptres['unidsc']. "</p>
                                                                                                                        <p><b>Programa: </b>". $ptres['prgcod']. ' &ndash; '. $ptres['prgdsc'].  "</p>
                                                                                                                        <p><b>A&ccedil;&atilde;o: </b>". $ptres['acacod']. ' &ndash; '. $ptres['acatitulo']. "</p>
                                                                                                                        <p><b>Localizador: </b>". $ptres['loccod']. ' &ndash; '. $ptres['locdsc'].  "</p>
                                                                                                                        <p><b>PO: </b>". $ptres['plocod']. ' &ndash; '. $ptres['plotitulo']. "</p>

                                                                                                                        <br>
                                                                                                                        <br>

                                                                                                                        <table border='1' cellpadding='0' cellspacing='0' style='margin: 0 auto; width:100%; border-color: #273a71;'>
                                                                                                                            <tbody>
                                                                                                                                <tr>
                                                                                                                                    <td>&nbsp;</td>
                                                                                                                                    <td>&nbsp;<span>Custeio</span></td>
                                                                                                                                    <td>&nbsp;<span>Capital</span></td>
                                                                                                                                </tr>
                                                                                                                                <tr>
                                                                                                                                    <td>&nbsp;<span>Valor</span></td>
                                                                                                                                    <td>&nbsp;<span class='valor'>R$ ". number_format($pi['picvalorcusteio'], 2, ',', '.'). "</span></td>
                                                                                                                                    <td>&nbsp;<span class='valor'>R$ ". number_format($pi['picvalorcapital'], 2, ',', '.'). "</span></td>
                                                                                                                                </tr>

                                                                                                                            </tbody>
                                                                                                                        </table>
                                                                                                                        <br>
                                                                                                                        <br>
                                                                                                                        <br>
                                                                                                                        <div class='assinatura'>
                                                                                                                            <p><b>". $acao. " por: </b>". $usuario['usunome']. "</p>
                                                                                                                            <p><b>Fone: </b><a>". $usuario['telefone']. "</a></p>
                                                                                                                            <p><b>Email: </b><a>". $usuario['usuemail']. "</a></p>

                                                                                                                        </div>

                                                                                                                    </div>
                                                                                                                </div>
                                                                                                            </div>
                                                                                                        </div>
                                                                                                    </td>
                                                                                                    <td valign='top' width='75' class='specbundle'>&nbsp;</td>
                                                                                                    <td class='specbundle'>
                                                                                                        <div class='contentEditableContainer contentTextEditable'>
                                                                                                            <div class='contentEditable' style='text-align: left;'>


                                                                                                                <br>
                                                                                                            </div>
                                                                                                        </div>
                                                                                                    </td>
                                                                                                </tr>
                                                                                            </tbody>
                                                                                        </table>
                                                                                    </td>
                                                                                </tr>
                                                                            </tbody>
                                                                        </table>


                                                                    </div>



                                                                </td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                                <td valign='top' width='20'>&nbsp;</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
</body>

";