<?php 
define("FUNCAO_PROFESSOR_PESQUISADOR_ESCOLA_ATIVA", 71);
define("FUNCAO_SUPERVISOR_ESCOLA_ATIVA", 72);
define("FUNCAO_PROFESSOR_MULTIPLICADOR_ESCOLA_ATIVA", 73);


define( "EA_TIPO_DOCUMENTO", 20 );

/*
 * PERFILS
 */
define("ESCOLAATIVA_PERFIL_SUPER_USUARIO", 440);
define("ESCOLAATIVA_PERFIL_ADMINISTRADOR", 442);
define("ESCOLAATIVA_PERFIL_COORDENADOR_MEC", 443);
define("ESCOLAATIVA_PERFIL_PESQUISADOR", 444);
define("ESCOLAATIVA_PERFIL_SUPERVISOR", 445);
define("ESCOLAATIVA_PERFIL_MULTIPLICADOR", 446);
define("ESCOLAATIVA_PERFIL_TECNICO_SECAD", 447);

/*** ESTADOS WORKFLOW ***/
if( $_SESSION['baselogin'] == 'simec_desenvolvimento' ){
	define("WF_EM_PREENCHIMENTO", 170);
	define("WF_EM_ANALISE_SEDUC", 171);
	define("WF_EM_ANALISE_IPES", 172);
	define("WF_EM_ANALISE_MEC", 173);
	define("WF_ENVIADO_SGB", 174);
	define("WF_HOMOLOGACAO_SGB", 178);
} else{
	define("WF_EM_PREENCHIMENTO", 222);
	define("WF_EM_ANALISE_SEDUC", 223);
	define("WF_EM_ANALISE_IPES", 224);
	define("WF_EM_ANALISE_MEC", 225);
	define("WF_ENVIADO_SGB", 226);
	define("WF_HOMOLOGACAO_SGB", 227);
}


?>