<?php 

#TIPO DE DOCUMENTO do módulo
define("TPDID_PNLD", 54);

#SISID do módulo
define("SISID_PNLD", 88);

#PERFIL do módulo
define("PNLD_SUPER_USER", 492 );
define("PNLD_PERFIL_GESTOR", 661 );
define("PNLD_PERFIL_TECNICO", 662 );
define("PNLD_PERFIL_COORDENADOR", 663 );
define("PNLD_EDITORA", 664 );
define("PNLD_PERFIL_PARECERISTA", 770 );


if ($_SESSION['baselogin'] == 'simec_desenvolvimento'){
    define("PNLD_EDITORA_EJA", 1077 );
    define("PNLD_PERFIL_GESTOR_EJA", 1076 );
    define("PNLD_PERFIL_COMISSAO_TECNICA", 1114 );
    define("PNLD_PERFIL_EDITORA_PNIAC", 1282);
    define("PNLD_PERFIL_GESTOR_PNIAC", 1283);
    define("PNLD_PERFIL_GESTOR_PTA", 1322);
    define("PNLD_PERFIL_UNIVERSIDADE_PTA", 1323);
    define("PNLD_PERFIL_GESTOR_CAMPO", 1349);
    define("PNLD_PERFIL_EDITORA_CAMPO", 1350);
}else{
    define("PNLD_EDITORA_EJA", 1084 );
    define("PNLD_PERFIL_GESTOR_EJA", 1085 );
    define("PNLD_PERFIL_COMISSAO_TECNICA", 1133 );
    define("PNLD_PERFIL_EDITORA_PNIAC", 1282);
    define("PNLD_PERFIL_GESTOR_PNIAC", 1283);
    define("PNLD_PERFIL_GESTOR_PTA", 1322);
    define("PNLD_PERFIL_UNIVERSIDADE_PTA", 1323);
    define("PNLD_PERFIL_GESTOR_CAMPO", 1349);
    define("PNLD_PERFIL_EDITORA_CAMPO", 1350);
}

#WORK FLOW DO MODULO PNLD.
define("PARECER_APROVACAO_CONDICIONADA", 2 );
define("PARECER_EXCLUSAO", 3 );

#Questionário PNLID.
define("PNLD_QUESTIONARIO", 80 );

#*******************************************************************************#
# DATA ALTERADA DEVIDO A ALTERAÇÃO NA FORMA QUE É FEITA A ANEXAÇÃO DOS ARQUIVOS.#
# REGRAS DE PERFIL QUE TERA O ACESSO AO BOTAO ANEXAR. COMENTARIO FEITO NO BOTAO.#
# DATA ANTERIOR: 2012-04-10. TAMBÉM FOI ALTERO O CÓDIGO DE ARQUIVO              #
# ANTES ESTAVA NO ARQUIVO pnld_resenha_colecao.inc AGORA AQUI EM _contantes.php #
#*******************************************************************************#

#DATA DE ABERTURA PARA VISUALIZAR PARECER.
define("DATA_ABERTURA_VISUALIZA_PARECER", 'June 29 2015 20:00');

#DATA DE ENCERRAMENTO PARA VISUALIZAR PARECER.
define("DATA_ENCERRAMENTO_VISUALIZA_PARECER", 'dec 31 2015 23:59');

#DATA DE ABERTURA PARA ANEXAR RECURSOS DA EDITORA.
//define("DATA_ABERTURA_RECURSO_EDITORA", '2015-06-29 17:00');
define("DATA_ABERTURA_RECURSO_EDITORA", '2015-06-25');
#DATA DE ENCERRAMENTO PARA ANEXAR RECURSOS DA EDITORA.
define("DATA_ENCERRAMENTO_RECURSO_EDITORA", '2015-07-10');

#DATA DE ABERTURA PARA ACESSO AO AMBIENTE RECURSO E RESPOSTA AO RECURSO DOS PERFIS COORDENADORES E TECNICOS.
define("DATA_ABERTURA_RECURSO_RESPOSTA_COORD_TEC", '2015-22-06');
#DATA DE ENCERRAMENTO PARA ACESSO AO AMBIENTE RECURSO E RESPOSTA AO RECURSO DOS PERFIS COORDENADORES E TECNICOS.
define("DATA_ENCERRAMENTO_RECURSO_RESPOSTA_COORD_TEC", '2015-12-30');

?>