<?php 
    if( $_SESSION['baselogin'] == "simec_desenvolvimento" ){

        define("PERFIL_GDOCUMENTO_SUPER_USUARIO", 763);
        define("PERFIL_GDOCUMENTO_COORDENACAO_GERAL", 929);
        define("PERFIL_GDOCUMENTO_APOIO", 930);
        define("PERFIL_GDOCUMENTO_ADMINISTRADOR", 931);
        define("PERFIL_GDOCUMENTO_ESQUIPE_TEC", 932);
        define("PERFIL_GDOCUMENTO_DIRETORIA", 933);
        
        #CONSTANTES DO WORKFLOW - GESTÃO DE DOCUMENTOS.
        define("FUXO_GESTAO_DOCUMENTOS", 121);
        
        #CONSTANTES DO WORKFLOW - ESTADOS DOCUMENTOS.
        define("WF_EM_PREENCHIMENTO_APOIO", 759);
        define("WF_EM_PREENCHIMENTO_COORDENACAO", 760);
        define("WF_PROCESSO_FINALIZADO", 761);
        define("WF_EM_PREENCHIMENTO_TCENICOS", 762);
        define("WF_EM_REVISAO_COORDENACAO", 764);
        define("WF_PROVIDENCIA_REVISAO_EQUIPE_TECNICA", 765);
        define("WF_IMPRESSAO_ASSINATURA_EQUIPE_TECNICA", 770);
        define("WF_PROCESSO_ARQUIVADO", 779);
        define("WF_ASSINATURA_COORDENACAO", 850);

    }else{
        
        define("PERFIL_GDOCUMENTO_SUPER_USUARIO", 763);
        define("PERFIL_GDOCUMENTO_APOIO", 1013);
        define("PERFIL_GDOCUMENTO_COORDENACAO_GERAL", 1014);
        define("PERFIL_GDOCUMENTO_DIRETORIA", 1016);
        define("PERFIL_GDOCUMENTO_ESQUIPE_TEC", 1017);
        define("PERFIL_GDOCUMENTO_ADMINISTRADOR", 1018);
        
        #CONSTANTES DO WORKFLOW - GESTÃO DE DOCUMENTOS.
        define('FUXO_GESTAO_DOCUMENTOS', 135);
        
        #CONSTANTES DO WORKFLOW - ESTADOS DOCUMENTOS.
        define("WF_EM_PREENCHIMENTO_APOIO", 842);        
        define("WF_EM_PREENCHIMENTO_COORDENACAO", 843);
        define("WF_PROCESSO_FINALIZADO", 844);
        define("WF_EM_PREENCHIMENTO_TCENICOS", 845);
        define("WF_EM_REVISAO_COORDENACAO", 846);
        define("WF_PROVIDENCIA_REVISAO_EQUIPE_TECNICA", 847);
        define("WF_IMPRESSAO_ASSINATURA_EQUIPE_TECNICA", 848);
        define("WF_PROCESSO_ARQUIVADO", 849);
        define("WF_ASSINATURA_COORDENACAO", 850);

    }
?>