<?php
define('SISID_PLANEJAMENTO', 256);

define('PFL_SUPERUSUARIO', 1505);
define("PFL_SUBUNIDADE", 1509);
define("PFL_ADMINISTRADOR", 1510);

define("WF_TPDID_PREPI", 268);


define("ESD_PREPI_CADASTRAMENTO", 1790);
define("ESD_PREPI_AGUARDANDO_APROVACAO", 1789);
define("ESD_PREPI_AGUARDANDO_CORRECAO", 1788);
define("ESD_PREPI_APROVADO", 1787);
?>