<?php

define( "SISID_EE",	 				    175);

if( $_SESSION['baselogin'] == 'simec_desenvolvimento' ){
	
	// PERFIS
	define( "PERFIL_SUPER_USUARIO",	 			1075);
	define( "PERFIL_ADMINISTRADOR",			 	1081);
	define( "PERFIL_CADASTRADOR",	 			1079);
	define( "PERFIL_PARECERISTA_CONJUR", 		1084);
	define( "PERFIL_PARECERISTA_CNE", 			1083);
	define( "PERFIL_APROVADOR_SEB", 			1082);
	define( "PERFIL_INTERESSADO", 			'');
	/*
	define( "PERFIL_CONSULTA",			 		716);
	define( "PERFIL_SEC_ESTADUAL", 				717);
	define( "PERFIL_SEC_MUNICIPAL",				718);
	define( "PERFIL_ANALISTA_SEDUC",			741);
	*/
	
	// WORKFLOW
	define( "WF_TPDID_EE", 						146);
	
	/*
	define( "WF_ESDID_FINALIZADO",	 			431);
	define( "WF_ESDID_EM_PREENCHIMENTO",	 	432);
	define( "WF_ESDID_EM_ANALISE_SEDUC", 		433);
	define( "WF_ESDID_EM_CORRECAO",	 			435);
	
	define( "WF_AEDID_RETURN_PREENCHIMENTO",   		249 );
	*/
	
	
}else{
	
	// PERFIS
	define( "PERFIL_SUPER_USUARIO",	 			1106);
	define( "PERFIL_ADMINISTRADOR",			 	1109);
	define( "PERFIL_CADASTRADOR",	 			1107);
	define( "PERFIL_PARECERISTA_CONJUR", 		1112);
	define( "PERFIL_PARECERISTA_CNE", 			1111);
	define( "PERFIL_APROVADOR_SEB", 			1110);
	define( "PERFIL_INTERESSADO", 				1160);
	define( "PERFIL_VALIDADOR", 				1108);
	define( "PERFIL_INTERESSADO", 				1160);
	define( "PERFIL_HOMOLOGADOR", 				1113);
	define( "PERFIL_CADASTRADOR_INEP", 			1114);
	define( "PERFIL_CONSULTA", 					1159);
	
	
	// WORKFLOW
	define( "WF_TPDID_EE", 						153);
	
	define( "WF_ESDID_EM_CADASTRAMENTO", 				974);
	define( "WF_ESDID_AGUARDANDO_VALIDACAO_EMBAIXADA", 	975);
	define( "WF_ESDID_AGUARDANDO_ANALISE_NA_ASSESSORIA_INTERNACIONAL", 	976);
	define( "WF_ESDID_AGUARDANDO_APROVACAO_NA_SEB", 	977);
	define( "WF_ESDID_AGUARDANDO_PARECER_CNE", 			978);
	define( "WF_ESDID_AGUARDANDO_PARECER_CONJUR", 		979);
	define( "WF_ESDID_AGUARDANDO_HOMOLOGACAO_NO_GABINETE_DO_MINISTRO", 	980);
	define( "WF_ESDID_AGUARDANDO_CADASTRO_INEP", 		981);
	define( "WF_ESDID_FINALIZADO", 						982);
	define( "WF_ESDID_EM_AJUSTES", 						983);

	define( "WF_AEDID_PARA_VALIDACAO_EMBAIXADA", 						2239);
	define( "WF_AEDID_PARA_AJUSTES_NO_CADASTRO", 						2240);
	define( "WF_AEDID_PARA_ANALISE_ASSESSORIA_INTERNACIONAL", 			2241);
	define( "WF_AEDID_PARA_DOCUMENTACAO_COMPLEMENTAR", 					2242);
	define( "WF_AEDID_PARA_PARECER_CNE", 								2243);
	define( "WF_AEDID_PARA_APROVACAO_NA_CEB", 							2244);
	define( "WF_AEDID_PARA_CADASTRAMENTO_INEP_NA_DCEI", 				2245);
	define( "WF_AEDID_PARA_INSERIR_NOVA_NOTA_TECNICA_DESPACHO_REGULARIDADE",	2246);
	define( "WF_AEDID_PARA_ANALISE_ASSESSORIA_INTERNACIONAL_DE_SEB", 	2247);
	define( "WF_AEDID_PARA_PARECER_CONJUR", 							2248);
	define( "WF_AEDID_PARA_PARECER_CNE", 								2249);
	define( "WF_AEDID_PARA_ANALISE_ASSESSORIA_INTERNACIONAL_DE_CNE", 	2250);
	define( "WF_AEDID_PARA_HOMOLOGACAO_NO_GABINETE_DO_MINISTRO", 		2251);
	define( "WF_AEDID_PARA_CRIAR_PROCESSO_CONJUR", 						2252);
	define( "WF_AEDID_PARA_INSERIR_PARECER_CONJUR", 					2253);
	define( "WF_AEDID_PARA_HOMOLOGAR_PARECER_CNE_PENDENTE", 			2254);
	define( "WF_AEDID_PARA_CADASTRAMENTO_INEP_NA_SEB", 					2255);
	define( "WF_AEDID_PARA_FINALIZAR", 									2256);
	define( "WF_AEDID_PARA_COORDENACAO_GERAL_DO_ENSINO_MEDIO", 			2257);
	define( "WF_AEDID_PARA_COORDENACAO_GERAL_DO_ENSINO_FUNDAMENTAL", 	2258);
	define( "WF_AEDID_PARA_COORDENACAO_GERAL_DA_EDUCACAO_INFANTIL", 	2259);
	define( "WF_AEDID_PARA_VALIDACAO_EMBAIXADA_DE_AJUSTES",				2260);

	
}

	// TIPO DE DOCUMENTO DA ESCOLA
    define( "TPD_COMPROVACAO",     1);
    define( "TPD_DESCRICAO",       7);
    define( "TPD_ORGANIZACAO",     3);
    define( "TPD_PROPOSTA",        2);
    define( "TPD_REGIMENTO",       4);
	define( "TPD_PARECER_CONJUR", 10);
	define( "TPD_PARECER_CNE",     9);
	define( "TPD_NOTA_TECNICA",    8);
	define( "TPD_DESPACHO",       11);
    define( "TPD_HOMOLOGACAO",    12);
    define( "TPD_OUTROS",         13);

?>