<?php
/**
  * CONSTANTES DO PROCESSO PARA IDENTIFICAR QUAL TIPO DE EXECUวรO.
*/
define("SUBACOES_GENERICO_PAR", 1);
define("OBRAS_PAR", 2);
define("OBRAS_PAC", 3);
define("SUBACOES_PAR_EMENDAS", 4);
define("EMENDAS_PARLAMENTARES", 5);
/*define("SUBACOES_PAR_BRASILPRO", 5);
define("OBRAS_PAR_BRASILPRO", 6);
define("SUBACOES_BRASILPRO", 7);
define("OBRAS_BRASILPRO", 8);
define("OBRAS_EMENDAS", 9);
define("GENERICO_EMENDAS", 10);*/
	
define("CONVENIO", 2);
define("TRANSFERENCIA_DIRETA", 1);

#				PERFIL
define("EXEC_PERFIL_SUPER_USUARIO", 	784);
define("EXEC_PERFIL_ADMINISTRADOR", 	817);
define("EXEC_PERFIL_TECNICO_EMPENHO", 	816);
define("EXEC_PERFIL_TECNICO_PAGAMENTO", 818);
define("EXEC_PERFIL_TECNICO_DOCUMENTO", 819);
?>