<?PHP
#DATA DE ACESSO AO NOVO CADASTRO DE INFRA, ACORDO COM NOVAS REGRAS DO EVENTOS.
define("DATA_NOVO_REGRA_EVENTO_NOVA_INFRA", '2014-09-01');

#COSNTANTES-ABAS DO SISTEMA.
define("ABA_CADASTRO_PREGAO_CONTRAT_UNI",57839);

#SISTEMA
define("EVT_SISID", 21);

define("PERFIL_SUPER_USUARIO", 255);

define("PERFIL_SEE", 351);
define("PERFIL_DEMANDANTE", 352);
define("PERFIL_SAA", 353);
define("PERFIL_CGCC", 354);
define("PERFIL_INSTITUICAO", 382);
define("PERFIL_EMPRESA", 292);

define("CADASTRAMENTO_WF", 113);
define("ANALISE_SECRETARIA_WF", 114);
define("AVALIACAO_SAA_WF", 115);
define("ASSINATURA_COORDENADOR_WF", 116);
define("EMISSAO_OS_WF", 117);
define("CADASTRAMENTO_INFRA_ESTRUTURA_WF", 118);
define("AGUARDANDO_APROVACAO_CORD_WF", 131);
define("EM_ANALISE_SAA_WF", 132);

//Estadosworkflow
define("EM_CADASTRAMENTO_WF", 113);
define("EM_ANALISE_COMITE_WF", 114);
define("APROVADO_PELO_COMITE_WF", 115);
define("PROCESSO_ABERTO_WF", 156);
define("ADEQUACAO_PROJETO_WF", 126);
define("PROJETO_FINALIZADO_WF", 127);
define("ELABORACAO_CDO_WF", 128);
define("EMISSAO_CDO_WF", 129);
define("INSTRUCAO_PROCESSO_WF", 130);
define("EMISSAO_EMPENHO_WF", 161);
//define("EMISSAO_OS_WF", 131);//DUPLICADO117
define("EVENTO_WF", 132);
define("EMISSAO_NF_WF", 133);
define("ATESTO_NF_WF", 134);
define("PAGAMENTO_NF_WF", 129);
define("AGUARDANDO_EXECUCAO_EVENTO_WF", 615);
define("AGUARDANDO_PAGAMENTO_EVENTO_WF", 614);


#AÇÃOESTADODOCUMENTO.
define("ACAO_REGISTRAR_PAGAMENTO", 1565);


define("MAX_EVENTOS_SEM_NOTA", 2);

define("ID_NOTA_TECNICA", 1);
define("ID_PROJETO_BASICO", 2);
define("ID_OUTROS", 3);
define("ID_TERMO_REFERENCIA", 4);
define("ID_PROPOSTA_SERVICO", 5);
define("ID_PORTARIA_FISCAL", 6);
define("ID_EDITAL", 7);
define("ID_CONTRATO", 8);
define("ID_ATA_REGISTRO_PRECO", 9);
define("ID_PARECER_CONJUR", 10);
define("ID_QUESTIONAMENTOS", 11);
define("ID_RESP_QUESTIONAMENTOS", 12);
define("ID_RELATORIO_ADJUDICACAO", 13);
define("ID_RELATORIO_HOMOLOGACAO", 14);
define("ID_TERMO_ADITIVO", 15);

define('REMETENTE_WORKFLOW_EMAIL', $_SESSION['email_sistema']);
define('REMETENTE_WORKFLOW_NOME', SIGLA_SISTEMA. '-MódulodeEventos');

define('WF_TPDID_COMPRAS', 6);
define('WF_TPDID_EVENTOS', 36);

define("EVENTO_PERFIL_CGCC", 354);
define("EVENTO_PERFIL_SAA", 353);
define("EVENTO_PERFIL_CADASTRADOR", 352);
define("EVENTO_PERFIL_SEC_EXECUTIVA_EVENTOS", 351);
define("EVENTO_PERFIL_CONSULTA", 268);
define("EVENTO_PERFIL_SUPER_USUARIO", 255);
define("EVENTO_PERFIL_ORDENADOR_DESPESA_COMPRAS", 263);
define("EVENTO_PERFIL_DEMANDANTE_COMPRAS", 262);
define("EVENTO_PERFIL_CONSULTA_COMPRAS", 291);
define("EVENTO_PERFIL_PERFIL_EMPRESA", 292);
define("EVENTO_PERFIL_SAA_FINANCEIRO", 432);
define("EVENTO_PERFIL_SAA_ORCAMENTO", 474);
define("EVENTO_PERFIL_FISCAL_EVENTO", 878);

#WORKFLOWSOLICITAÇÃODEDIÁRIAS
define("WF_SOLICITAÇÃO_DIARIAS", 42);
define("WF_SOLICITAÇÃO_DIARIAS_EM_SOLICITACAO", 290);
define("WF_SOLICITAÇÃO_DIARIAS_EM_VERIFICACAO", 291);
define("WF_SOLICITAÇÃO_DIARIAS_EM_AUTORIZACAO", 292);
define("WF_SOLICITAÇÃO_DIARIAS_EM_PAGAMENTO", 293);
define("WF_SOLICITAÇÃO_DIARIAS_PAGO", 298);
define("WF_SOLICITAÇÃO_CANCELADA", 304);
define("WF_SOLICITAÇÃO_AGUARDANDO_DEVOLUCAO", 311);
define("WF_SOLICITAÇÃO_DEVOLUCAO_EFETUADA", 312);
define("WF_SOLICITACAO_EXCLUIDA", 318);
define("WF_SOLICITACAO_COMPLEMENTADA", 319);

#PRFILSOLICITAÇÃODEDIÁRIAS
define("EVENTO_PERFIL_SOLICITADOR", 535);
define("EVENTO_PERFIL_VALIDADOR", 536);
define("EVENTO_PERFIL_AGENTE_FINANCEIRO", 537);
define("EVENTO_PERFIL_AUTORIZADOR", 538);
define("EVENTO_PERFIL_ADMINISTRADOR_DIARIAS", 541);

#PRFILENVIARPARAPAGAMENTO
if($_SESSION['baselogin']=='simec_desenvolvimento'){
    define("EVENTO_PERFIL_DRP", 784);
}else{
    define("EVENTO_PERFIL_DRP", 768);
}

?>