<?php
//Tipologia da Obra
define("OBRA_TIPO_A",		16);
define("OBRA_TIPO_B",		9);
define("OBRA_TIPO_C",		10);
define("OBRA_TIPO_C",		10);
define("OBRA_TIPO_C",		10);
define("MI_OBRA_TIPO_B",	104);
define("MI_OBRA_TIPO_C",	105);
define("ESPACO_EDUCATIVO",	1);
define("ANO_TRAVA_SISTEMA",	2015);

//Programa Fonte

define("PRF_PROINFANCIA",41);

//WorkFlow
define("WF_TPDID_PROINFANTIL_NOVASTURMAS",	78);
define("WF_TPDID_SUPLEMENTACAO_MDS",		79);
define("WF_PROINFANTIL",					48);

//Estados Workflow Obras 2
define("OBR2_ESDID_OBJ_EXECUCAO", 690);
define("OBR2_ESDID_OBJ_CONCLUIDO", 693);

// Estados Workflow
define("WF_PROINFANTIL_EM_CADASTRAMENTO",369);
define("WF_PROINFANTIL_EM_ANALISE",370);
define("WF_PROINFANTIL_ENVIADO_PARA_PAGAMENTO",372);
define("WF_PROINFANTIL_ANALISADO",687);
define("WF_PROINFANTIL_PAGAMENTO_EFETUADO",373);
define("WF_PROINFANTIL_EM_VALIDACAO_DE_ANALISE",407);
define("WF_PROINFANTIL_OBRA_ARQUIVADA",517);
define("WF_PROINFANTIL_OBRA_ARQUIVADA_SISTEMA",1106);
define("WF_PROINFANTIL_EM_DILIGENCIA",518);

define ("AEDID_PRO_ENCAMINHAR_AGUARDANDO_PAGAMENTO",	1760);
define ("AEDID_PRO_ENCAMINHAR_PAGAMENTO_EFETUADO",		1034);
define ("AEDID_PRO_ENCAMINHAR_DILIGENCIA",				1033);
define ("AEDID_PRO_DILIGENCIA_ENVIAR_ANALISE",			1373);
define("AEDID_PRO_DILIGENCIA_INDEFERIR_ARQUIVADO_SISTEMA",	2578);
if( $_SESSION['baselogin'] == 'simec_desenvolvimento' ){
	define("AEDID_PRO_DILIGENCIA_INDEFERIR",	2144);
	define("AEDID_PRO_CADASTRAMENTO_INDEFERIR",	2145);
}else{
	define("AEDID_PRO_DILIGENCIA_INDEFERIR",	2227);
	define("AEDID_PRO_CADASTRAMENTO_INDEFERIR",	2238);
}


// fluxo mds
if( $_SESSION['baselogin'] == 'simec_desenvolvimento' ){
	define("WF_MDS_EM_CADASTRAMENTO",	504);
	define("WF_MDS_EM_ANALISE",			509);
	define("WF_MDS_EM_DIGILENCIA",		541);
}else{
	define("WF_MDS_EM_CADASTRAMENTO",	  538);
	define("WF_MDS_EM_ANALISE",			  539);
	define("WF_MDS_PAGAMENTO_EFETUADO",	  540);
	define("WF_MDS_EM_DIGILENCIA",		  541);	
	define("WF_MDS_EM_VALIDACAO",	      542);	
	define("WF_MDS_ANALISADO",			  543);	
	define("WF_MDS_AGUARDANDO_PAGAMENTO", 558);
	define("WF_MDS_INDEFERIDO_ARQUIVADO_SISTEMA", 1086);
}
 
define ("AEDID_MDS_ENCAMINHAR_AGUARDANDO_PAGAMENTO",1410);
define ("AEDID_MDS_ENCAMINHAR_PAGAMENTO_EFETUADO",1443);
define ("AEDID_MDS_ENCAMINHAR_ANALISE_DILIGENCIA",1404);
define ("AEDID_MDS_ENCAMINHAR_DILIGENCIA_ANALISE",1407);

// fluxo novas turmas
define("WF_NOVASTURMAS_EM_CADASTRAMENTO",535);
define("WF_NOVASTURMAS_EM_ANALISE",536);
define("WF_NOVASTURMAS_EM_VALIDACAO_DE_ANALISE",537);
define("WF_NOVASTURMAS_EM_INDEFERIDO_ARQUIVADO",658);
define("WF_NOVASTURMAS_EM_DILIGENCIA",587);
define("WF_NOVASTURMAS_EM_APROVADA",877);
define("WF_NOVASTURMAS_AGUARDANDO_PAGAMENTO",586);
define("WF_NOVASTURMAS_PAGAMENTO_EFETUADO",599);
define("WF_NOVASTURMAS_EM_INDEFERIDO_ARQUIVADO_SISTEMA",1073);

define ("NOVASTURMAS_ENCAMINHAR_AGUARDANDO_PAGAMENTO", 	1546);
define ("NOVASTURMAS_ENCAMINHAR_PAGAMENTO_EFETUADO", 	1548);
define ("NOVASTURMAS_ENVIAR_DILIGENCIA", 				1526);
define ("NOVASTURMAS_RETORNAR_ANALISE", 				1547);

//Questionαrio proinfancia
if( $_SESSION['baselogin'] == 'simec_desenvolvimento' ){
	define("QUESTIONARIO",109);
} else {
	define("QUESTIONARIO",62);
}

//Questionαrio Novas Turmas
if( $_SESSION['baselogin'] == 'simec_desenvolvimento' ){
	define("QUESTIONARIONOVASTURMAS",79);
} else {
	define("QUESTIONARIONOVASTURMAS",80);
}

//Questionαrio Suplementaηγo MDS
if( $_SESSION['baselogin'] == 'simec_desenvolvimento' ){
	define("QUESTIONARIOMDS",80);
} else {
	define("QUESTIONARIOMDS",80);
}

define('AEDID_ENVIAR_ANALISE', 1402);

define ("PERFIL_ADMINISTRADOR",609);
define ("PERFIL_ANALISTA",675);
define ("CONSULTA_GERAL",551);
define ("PERFIL_COORDENADOR",666);
define ("EQUIPE_MUNICIPAL",549);
define ("PERFIL_SUPER_USUARIO",547);
define ("PERFIL_ANALISTA_PAGAMENTO",806);
define ("SECRETARIO_ESTADUAL",840);

define("QUESTAO_02",1800);

//WORKFLOW MDS
	define ("AEDID_MDS_ENCAMINHAR_ANALISADO",1410);
	define ("AEDID_MDS_ENCAMINHAR_PAGAMENTO_EFETUADO",1443);
	
	define ("ESDID_MDS_ANALISADO",543);
	define ("ESDID_MDS_AGUARDANDO_PAGAMENTO",558);
	
	
//FIM WORKFLOW MDS

// NOVAS TURMAS
if( $_SESSION['baselogin'] == 'simec_desenvolvimento' ){
	define('QUEID_NOVASTURMAS_ATENDIMENTO', 	83);
	define('PERID_NT_ATEND_DESABILITA_PERG', 	3274);
	define('PERID_NT_ATEND_DESABILITA_RESP', 	4232);
	define('PERID_NT_ATENDIMENTO_EXTERNO1', 	3302);
	define('PERID_NT_ATENDIMENTO_EXTERNO2', 	3308);
} else {
	define('QUEID_NOVASTURMAS_ATENDIMENTO', 	80);
	define('PERID_NT_ATEND_DESABILITA_PERG', 	3039);
	define('PERID_NT_ATEND_DESABILITA_RESP', 	4074);
	define('PERID_NT_ATENDIMENTO_EXTERNO1', 	3040);
	define('PERID_NT_ATENDIMENTO_EXTERNO2', 	3041);	
}

define('TIPO_DEP_EXCLUSIVO_CRECHE', 	1);
define('TIPO_DEP_EXCLUSIVO_PREESCOLA', 	2);
define('TIPO_DEP_UNIFICADO', 			3);

define('TIPO_REDE_PUBLICA', 			1);
define('TIPO_REDE_PRIVADA', 			2);

define('PREESCOLA',	1);
define('CRECHE',	3);



