<?php
//Sistema
define( "CTE_SISTEMA", 13 );

// Perfil
define( "CTE_PERFIL_EQUIPE_MUNICIPAL", 130 );
define( "CTE_PERFIL_EQUIPE_LOCAL", 124 );
define( "CTE_PERFIL_EQUIPE_ESTADUAL_CADASTRO", 124 );
define( "CTE_PERFIL_EQUIPE_LOCAL_APROVACAO", 128 );
define( "CTE_PERFIL_EQUIPE_TECNICA", 125 );
define( "CTE_PERFIL_EQUIPE_TECNICA_FORMACAO_ESCOLA", 428 );
define( "CTE_PERFIL_EQUIPE_ESCOLA_ATIVA", 288 );
define( "CTE_PERFIL_CONSULTORES", 126 );
define( "CTE_PERFIL_ALTA_GESTAO", 129 );
define( "CTE_PERFIL_CONSULTA_GERAL", 127 );
define( "CTE_PERFIL_ADMINISTRATOR_TEMP", 289 );
define( "CTE_PERFIL_ADMINISTRADOR_FINANCEIRO", 269 );
define( "CTE_PERFIL_PARECERISTA_FISICO_FINANCEIRO", 155 );

define( "CTE_PERFIL_CONSULTA_MUNICIPAL", 275 );
define( "CTE_PERFIL_CONSULTA_ESTADUAL", 276 );

define( "CTE_PERFIL_EQUIPE_TECNICA_FNDE", 167 );
define( "CTE_PERFIL_EQUIPE_TECNICA_MEC_MUN", 172 );
define( "CTE_PERFIL_PLAN_ESTRATEGICO_EST", 170 );
define( "CTE_PERFIL_PLAN_ESTRATEGICO_MUN", 171 );
 
define( "CTE_PERFIL_SUPER_USUARIO", 121 );
define( "CTE_PERFIL_ADMINISTRADOR", 147 );

// Estado Documento
define( "CTE_ESTADO_DIAGNOSTICO", 1 );
define( "CTE_ESTADO_PAR", 2 );
define( "CTE_ESTADO_ANALISE", 10 ); // assistъncia tщcnica
define( "CTE_ESTADO_ANALISE_FIN", 13 ); // assistъncia financeira
define( "CTE_ESTADO_FINALIZADO", 11 );
define( "CTE_ESTADO_PARECER", 14 );
define( "CTE_ESTADO_FNDE", 15 ); 

// Estado Documento Escola Ativa
define( "CTE_ESTADO_ESCOLA_ATIVA_EM_PREENCHIMENTO", 47 );
define( "CTE_ESTADO_ESCOLA_ATIVA_EM_ANALISE", 48 );
define( "CTE_ESTADO_ESCOLA_ATIVA_ANALISADO", 49 );
define( "CTE_ESTADO_ESCOLA_ATIVA_EM_REVISAO", 50 );
define( "CTE_ESTADO_ESCOLA_ATIVA_EM_CORRECAO", 51 );

// Instrumentos
define( "INSTRUMENTO_DIAGNOSTICO_ESTADUAL", 1 );
define( "INSTRUMENTO_DIAGNOSTICO_MUNICIPAL", 2 );
define( "CTE_OBRA_CONSTRUCAO", 1 );
define( "CTE_OBRA_REFORMA", 2 );
define( "CTE_OBRA_AMPLIACAO", 3 );

// Formas de execucao
define( "FORMA_EXECUCAO_ASS_TEC", 4 );
define( "FORMA_EXECUCAO_ASS_FIN", 3 );

// Unidades de Medida
define( "CTE_UNIDADE_MEDIDA_SERVIDOR_MUN", 174 );
define( "CTE_UNIDADE_MEDIDA_SERVIDOR_EST", 174 );
define( "CTE_UNIDADE_MEDIDA_TECNICO_MUN", 178 );
define( "CTE_UNIDADE_MEDIDA_TECNICO_EST", 178 );
define( "CTE_UNIDADE_MEDIDA_PROFESSOR_MUN", 157 );
define( "CTE_UNIDADE_MEDIDA_PROFESSOR_EST", 17 );
define( "CTE_UNIDADE_MEDIDA_PROFESSOR_MULTIPLICADOR_MUN", 597 );
define( "CTE_UNIDADE_MEDIDA_PROFESSOR_MULTIPLICADOR_EST", 598 );
define( "CTE_UNIDADE_MEDIDA_PROFESSOR_CURSISTA_MUN", 599 );
define( "CTE_UNIDADE_MEDIDA_PROFESSOR_CURSISTA_EST", 600 );
define( "CTE_UNIDADE_MEDIDA_PROFESSOR_TUTOR_MUN", 603 );
define( "CTE_UNIDADE_MEDIDA_PROFESSOR_TUTOR_EST", 604 );
define( "CTE_UNIDADE_MEDIDA_ESCOLA_MULTISSERIADA_MUN", 601 );
define( "CTE_UNIDADE_MEDIDA_ESCOLA_MULTISSERIADA_EST", 602 );
define( "CTE_UNIDADE_MEDIDA_DIRETOR_MUN", 324 );
define( "CTE_UNIDADE_MEDIDA_DIRETOR_EST", 7 );
define( "CTE_UNIDADE_MEDIDA_CONSELHEIRO_MUN", 323 );
define( "CTE_UNIDADE_MEDIDA_CONSELHEIRO_EST", 5 );
define( "CTE_UNIDADE_MEDIDA_FUNCIONARIO_MUN", 314 );
define( "CTE_UNIDADE_MEDIDA_FUNCIONARIO_EST", 11 );
define( "CTE_UNIDADE_MEDIDA_UNIDADES_ESCOLARES_MUN", 322 );
define( "CTE_UNIDADE_MEDIDA_UNIDADES_ESCOLARES_EST", 22 );
define( "CTE_UNIDADE_MEDIDA_SERVIDOR_SME", 317 );
define( "CTE_UNIDADE_MEDIDA_REUNIOES", 316 );
define( "CTE_UNIDADE_MEDIDA_DOCUMENTOS", 296 );

define( "CTE_UNIDADE_MEDIDA_KIT_MATERIAL", 313 );
define( "CTE_UNIDADE_MEDIDA_DIAGNOSTICO", 312 );

// Tipo de Dados da Unidade
define( "CTE_TIPO_DADOS_UNIDADE_ORGAO_MUNICIPAL", 1 );
define( "CTE_TIPO_DADOS_UNIDADE_DIRIGENTE_MUNICIPAL", 2 );
define( "CTE_TIPO_DADOS_UNIDADE_EQUIPE_LOCAL", 3 );
define( "CTE_TIPO_DADOS_UNIDADE_COMITE_LOCAL", 4 );
define( "CTE_TIPO_DADOS_UNIDADE_COMITE_LOCAL_COORDENADOR", 5 );

// Situaчуo da Сrvore na Subaчуo
define( "CTE_SITUACAO_ARVORE_PRINCIPAL", 1 );
define( "CTE_SITUACAO_ARVORE_ESCOLA_ATIVA", 2 );
define( "CTE_SITUACAO_ARVORE_AMBAS", 3 );
define( "CTE_SITUACAO_ARVORE_PRO_LETRAMENTO", 4 );
define( "CTE_SITUACAO_ARVORE_PRINCIPAL_E_PRO_LETRAMENTO", 5 );
define( "CTE_SITUACAO_ARVORE_PRO_FUNCIONARIO", 6 );
define( "CTE_SITUACAO_ARVORE_PRINCIPAL_E_PRO_FUNCIONARIO", 7 );
define( "CTE_SITUACAO_ARVORE_FORMACAO_ESCOLA", 8 );
define( "CTE_SITUACAO_ARVORE_PRINCIPAL_E_FORMACAO_ESCOLA", 9 );

// Situaчуo da Сrvore na Subaчуo
define( "CTE_FILTRO_ARVORE_PRINCIPAL", 1 );
define( "CTE_FILTRO_ARVORE_ESCOLA_ATIVA", 2 );
define( "CTE_FILTRO_ARVORE_PRO_LETRAMENTO", 3 );
define( "CTE_FILTRO_ARVORE_TODAS", 4 );
define( "CTE_FILTRO_ARVORE_PRO_FUNCIONARIO", 5 );
define( "CTE_FILTRO_ARVORE_FORMACAO_ESCOLA", 6 );
define( "CTE_FILTRO_ARVORE_CONVENIO", 7 );
define( "CTE_FILTRO_QUESTIONARIO", 32 );

// Situaчуo da Adesуo de Escola Ativa
define( "CTE_ADESAO_ESCOLA_ATIVA_ACEITA", 1 );
define( "CTE_ADESAO_ESCOLA_ATIVA_NAO_ACEITA", 2 );
define( "CTE_ADESAO_ESCOLA_ATIVA_SEM_CLASSES", 3 );
define( "CTE_ADESAO_PRO_LETRAMENTO", 4 );
define( "CTE_ADESAO_PRO_FUNCIONARIO", 5 );
define( "CTE_ADESAO_FORMACAO_ESCOLA", 6 );
define( "CTE_ADESAO_ESCOLA_ATIVA_MULTISERIADAS", 7 ); 

// Tipos de Documento
define( "CTE_TIPO_DOCUMENTO_ESCOLA_ATIVA", 7 );

// Tipos de Subaчуo
define( "CTE_TIPO_SUBACAO_PROFESSOR", 1 );
define( "CTE_TIPO_SUBACAO_TECNICO", 2 );
define( "CTE_TIPO_SUBACAO_PREDIO", 3 );
define( "CTE_TIPO_SUBACAO_TURMA", 4 );
define( "CTE_TIPO_SUBACAO_ANO_1", 5 );
define( "CTE_TIPO_SUBACAO_ANO_2", 6 );
define( "CTE_TIPO_SUBACAO_ANO_3", 7 );
define( "CTE_TIPO_SUBACAO_ANO_4", 8 );
define( "CTE_TIPO_SUBACAO_ANO_5", 9 );

// Programas
define( "CTE_PROGRAMA_ESCOLA_ATIVA", 549 );

switch($_SESSION['baselogin']) {
	case 'simec_desenvolvimento':
		define( "CTE_ESTADO_FNDE", 75 ); 
		break; 
	
	case 'simec':	
	case 'simec2008':
	case 'simec_espelho_producao':	
		define( "CTE_ESTADO_FNDE", 15 ); 
		break;
}


?>