<?PHP
    if( $_SESSION['baselogin'] == 'simec_desenvolvimento' ){
        #PERFIS
	define ("CAP_PERFIL_SUPER_USUARIO", 1046);
	define ("CAP_PERFIL_SERVIDOR", 1047);
	define ("CAP_PERFIL_ADMINISTRADOR", 1048);
	define ("CAP_PERFIL_GABINETE", 1049);

        #WORKFLOW - TIPO DE DOCUMENTO
	define("WF_TPDID_CONTROLE_AFASTAMENTO",214);

        #WORKFLOW - ESTADO DOCUMENTO
	define("WF_CADASTRO_FORMULARIO_VAIAGEM",1302);
	define("WF_ANALISE_FORMULARIO_AI",1303);
	define("WF_CORRECOES_FORMULARIO_VIAGEM",1304);
	define("WF_RE_ANALISE_FORMULARIO_AI",1305);
	define("WF_ANALISE_GM_AUTORIZACAO",1306);
	define("WF_PREENC_RELATORIO_VIAGEM",1307);
	define("WF_ANALISE_RELATORIO_VIAGEM_AI",1308);
	define("WF_CORRECOES_RELATORIO_VIAGEM",1309);
	define("WF_RE_ANALISE_RELATORIO_VIAGEM_AI",1310);
	define("WF_ALTERAR_VIAGEM_AI",1311);
	define("WF_CANCELAR_VIAGEM_AI",1312);
	define("WF_ANALISE_GM_ALTERAR_VIAGEM_AI",1313);
	define("WF_ANALISE_GM_CANCELAR_VIAGEM_AI",1314);
	define("WF_VIAGEM_FINALIZADA",1315);
	define("WF_VIAGEM_CANCELADA",1316);
	define("WF_SUBSTITUIDO_NOVO_FORMULARIO",1333);
	define("WF_CADASTRO_NOVO_FORMULARIO", 1334);

        #WORKFLOW - AวรO

        #ABAS
	define ("ABA_PESQUISA", 57751);
	define ("ABA_CAD_AFASTAMENTO", 57753);

    }else{
        #PERFIS
	define ("CAP_PERFIL_SUPER_USUARIO", 1046);
	define ("CAP_PERFIL_SERVIDOR", 1047);
	define ("CAP_PERFIL_ADMINISTRADOR", 1048);
	define ("CAP_PERFIL_GABINETE", 1049);

        #WORKFLOW - TIPO DE DOCUMENTO
	define("WF_TPDID_CONTROLE_AFASTAMENTO",214);

        #WORKFLOW - ESTADO DOCUMENTO
	define("WF_CADASTRO_FORMULARIO_VAIAGEM",1382);
	define("WF_ANALISE_FORMULARIO_AI",1383);
	define("WF_CORRECOES_FORMULARIO_VIAGEM",1384);
	define("WF_RE_ANALISE_FORMULARIO_AI",1385);
	define("WF_ANALISE_GM_AUTORIZACAO",1386);
	define("WF_PREENC_RELATORIO_VIAGEM",1387);
	define("WF_ANALISE_RELATORIO_VIAGEM_AI",1388);
	define("WF_CORRECOES_RELATORIO_VIAGEM",1389);
	define("WF_RE_ANALISE_RELATORIO_VIAGEM_AI",1390);
	define("WF_ALTERAR_VIAGEM_AI",1391);
	define("WF_CANCELAR_VIAGEM_AI",1392);
	define("WF_ANALISE_GM_ALTERAR_VIAGEM_AI",1393);
	define("WF_ANALISE_GM_CANCELAR_VIAGEM_AI",1394);
	define("WF_VIAGEM_FINALIZADA",1395);
	define("WF_VIAGEM_CANCELADA",1396);
	define("WF_SUBSTITUIDO_NOVO_FORMULARIO",1397);
	define("WF_CADASTRO_NOVO_FORMULARIO", 1398);

        #WORKFLOW - AวรO

        #ABAS
	define ("ABA_PESQUISA", 57751);
	define ("ABA_CAD_AFASTAMENTO", 57753);
    }
?>