<?php
define("TIPODOC", 73);

define("ESDID_AUTUANDO_PROCESSO"			,490);
define("ESDID_AGUARDANDO_PROVIDENCIA"		,501);
define("ESDID_AGUARDANDO_RESPOSTA_EXTERNA"	,502);
define("ESDID_ARQUIVADO"					,503);
define("ESDID_ENCERRADO"					,504);
define("ESDID_DESARQUIVADO"					,505);
define("ESDID_EM_ANALISE_DO_PROCURADOR"		,506);
define("ESDID_EM_ANALISE_DO_GABINETE"		,507);

define("AEDID_ARQUIVAR_PROCESSO"			,1337);
define("AEDID_AGUARDAR_RESPOSTA_EXTERNA"	,1340);
define("AEDID_ENCERRAR_PROCESSO_1"			,1341);
define("AEDID_ENCERRAR_PROCESSO_2"			,1342);
define("AEDID_INICIAR_NOVA_TRAMITACAO"		,1343);
define("AEDID_ENCAMINHAR_PARA_PROCURADOR_1"	,1338);
define("AEDID_ENCAMINHAR_PARA_PROCURADOR_2"	,1344);
define("AEDID_ENCAMINHAR_PARA_PROCURADOR_3"	,1348);
define("AEDID_DESARQUIVAR_PROCESSO"			,1345);
define("AEDID_RETORNA_ESTADO_ANTERIOR_501"	,1350);
define("AEDID_ENCAMINHAR_PARA_GABINETE_1"	,1339);
define("AEDID_ENCAMINHAR_PARA_GABINETE_2"	,1346);
define("AEDID_ENCAMINHAR_PARA_APOIO"		,1336);
define("AEDID_RETORNAR_PARA_APOIO_1"		,1347);
define("AEDID_RETORNAR_PARA_APOIO_2"		,1349);

define("ORGCOD",							26000);
define("TIPOPRCJUDICIAL",					2);

define("PRF_SUPERUSUARIO",					746);
define("PRF_ADMINISTRADOR",					749);
define("PRF_PROCURADOR",					695);
define("PRF_APOIO",							753);
define("PRF_GABINETE",						747);

//Legado
define("PRF_TECNICO",						753);
define("PRF_ADMPROFEINEP",					749);
define("PRF_TECNICO_ADM",					748);
define("PRF_ADVOGADO",						750);
define("PRF_CONSULTAGERAL",					751);
define("PRF_APOIO_PROTOCOLO",				747);
define("PRF_APOIO_GABINETE",				752);
//Fim legado

define("FUN_PARTICIPANTEPROFEINEP",			50);

//
//Coordenações
//

define("COONID_COORDENAÇÃO_DE_APOIO_A_PROJUR"	,1);
define("COONID_PROCURADORES_PROJUR"				,2);
define("COONID_GABINETE_PROJUR"					,3);

?>