<?php
//Função Entidade
define("FUN_MANTENEDORA",101);
define("FUN_DIRIGENTE",97);
define("FUN_UNIVERSIDADE",12);

//Papel do Membro do Comitê Gestor
define("PAPEL_COORD_INSTITUCIONAL",9);
define("PAPEL_COORD_LICENCIATURA",1);
define("PAPEL_PRO_REITORIA_GRADUACAO",2);

//Perfil
//define("PERFIL_SUPER_USUARIO",679);
//define("PERFIL_ADMINISTRADOR",712);
define("PERFIL_SUPER_USUARIO",688);
define("PERFIL_ADMINISTRADOR",722);
define("PERFIL_EQUIPE_ESTADUAL_APROVACAO",709);
define("PERFIL_EQUIPE_ESTADUAL",711);
define("PERFIL_EQUIPE_MUNICIPAL_APROVACAO",708);
define("PERFIL_EQUIPE_MUNICIPAL",710);
define("PERFIL_CONSULTA",703);
define("PERFIL_DIRIGENTE",707);

//define("PERFIL_FORUM_APROVACAO",785);
//define("PERFIL_FORUM_DISTRIBUICAO",786);
define("PERFIL_FORUM_APROVACAO",772);
define("PERFIL_FORUM_DISTRIBUICAO",773);


//Workflow PDE Interativo
//define("WORKFLOW_PDE_INTERATIVO_EM_ANALISE_SNF",307); // apenas para teste, remover depois
define("WORKFLOW_PDE_INTERATIVO_EM_ANALISE_SNF",417);

//Workflow SNF
//define("WORKFLOW_SNF",57);//PARA USAR NO SERVIDOR DE DESENVOLVIMENTO.
define("WORKFLOW_SNF", 64);
define("WORKFLOW_SNF_DEFINIR_PRIORIDADE",1156);
define("WORKFLOW_SNF_DEVOLVER_ANALISE_PRIORIDADE",1176);
define("WORKFLOW_SNF_ESTADO_EM_ANALISE_SECRETARIA",425);
//define("WORKFLOW_SNF_EM_VALIDACAO_PELA_SECRETARIA", 425); //PARA USAR NO SERVIDOR DE DESENVOLVIMENTO.
define("WORKFLOW_SNF_EM_VALIDACAO_PELA_SECRETARIA", 463); //PARA USAR NO SERVIDOR DE PRODUÇÃO.
define("WORKFLOW_SNF_ENVIADO_AO_FORUM", 464); //PARA USAR NO SERVIDOR DE PRODUÇÃO.


define("MOD_PRESENCIAL", 1);

?>