<?php

// ESFERA DA AวรO
define( 'ESFERA_FEDERAL_BRASIL', 1 );
define( 'ESFERA_ESTADUAL_DISTRITO_FEDERAL', 2 );
define( 'ESFERA_MUNICIPAL', 3 );
define( 'ESFERA_EXTERIOR', 4 );


define("WF_TPDID_BENEFICIARIO", 267);

define("ESD_BENEFICIARIO_CADASTRAMENTO", 1781);
define("ESD_BENEFICIARIO_PREENCHIMENTO_UNIDADE", 1782);
define("ESD_BENEFICIARIO_CORRECAO", 1783);
define("ESD_BENEFICIARIO_PI_GERADO", 1784);